### ISSUE TITLE
translations.pro file

### ISSUE THREAD

**Issue by mehmetaksakal** [OpenBoard-org/OpenBoard#103]
In the Linux build.sh the following is present on line 151.

`$LRELEASES translations.pro`

The OSX script has something similar on line 157, but it's commented out.

`#$LRELEASE $BASE_QT_TRANSLATIONS_DIRECTORY/translations.pro`

Can't find anything in the Windows build script.

What is this translations.pro file and where can I get it?

**Comment by freeheel3r** [comment]
The `translations.pro` file this refers has to do with Qt's own translation files. This is so that things like standard dialogs (e.g the "open file" dialog), which are provided by Qt and not directly by OpenBoard, are translated correctly.

It changes from one system to the next. On Windows and macOS for example, Qt's translation files are already compiled and so we don't need to call `lrelease` on anything. We just copy over the `.qm` files we need.

1-line summary in case you're not familiar with Qt's translation system: Translations are written in plain text in `.ts` files; these files are then compiled by the Qt utility `lrelease` to give `.qm` files which can be bundled with the application.

Are you getting an error related to this line of the build script?

**Comment by mehmetaksakal** [comment]
Yeah it's giving a file not found error but after that goes along happily and finishes building. I'm unable to test the translations at the moment, but English everything looks just fine. I'll test whether everything is working and report back later.

**Comment by freeheel3r** [comment]
Ah. Maybe you're missing a package that provides the Qt translation files, or the `GUI_TRANSLATIONS_DIRECTORY_PATH` variable in `build.sh` isn't pointing to the correct folder.

Or maybe the .ts files are no longer provided. In that case you can just copy the .qm files from wherever they are (like with Windows and macOS). In that case you'd want to edit line 246 of `package.sh`.

**Comment by mehmetaksakal** [comment]
I've installed the qt5translations package and the translations folder is there. It's filled with *.qm files. it also has a folder called qtwebengines_locales which is filled with *.pak files.

I've quickly tested a few locales, Dutch, Turkish and French. All of them seem to work just fine. I did find a small glitch with the Dutch locale btw.

```
<message>
        <source>OpenBoard</source>
        <translation type="unfinished">Sankoré openen</translation>
</message
```
The OpenBoard menu at the topright is translated from "Open Sankoré" but it's translated in the context of opening a physical object like a door. It should be changed to "OpenBoard", just a small thing.

Apart from that all translations seem to work just fine. I think this is probably something that changed in QT 5.7 and it's probably mentioned in the docs somewhere but good luck finding it.

**Comment by mehmetaksakal** [comment]
You are right, only thing I needed todo is copy the qm files over. I've modified build.sh on line 155 like this:
```
#$LRELEASES translations.pro
cp $GUI_TRANSLATIONS_DIRECTORY_PATH/qt_??.qm $PRODUCT_PATH/i18n/
```

My package.sh already looks like this so didn't change anything.
```
notifyProgress "Copying Qt translations"
mkdir -p $PACKAGE_DIRECTORY/i18n
cp $GUI_TRANSLATIONS_DIRECTORY_PATH/qt_??.qm $PACKAGE_DIRECTORY/i18n/
```

I did however discover that the Dutch translation is incomplete and that's why some text is still showing up in English, will look at this at a later date when I have more time.
