### ISSUE TITLE
Documentation on setting up Windows build environment

### ISSUE THREAD

**Issue by mehmetaksakal** [OpenBoard-org/OpenBoard#105]
I have a few ideas I would like to implement within OB, mainly things concerning electrical engineering like SPICE, simulation and solving. Not sure what direction to take it yet, probably will be born out of my own needs. Something between [PartSim](https://www.partsim.com/examples/), [LabView](http://www.ni.com/nl-nl/shop/labview.html) and [Simulink](https://www.mathworks.com/products/simulink.html).

First things first, I will need a working build environment and I am 0 fimiliar with the QT toolbase. I'm using VS2017 and also have a VS2015 license (but not installed).

I've installed QTCreater but had 0 luck getting that to work. Any pointers, guides or howto's?

**Comment by freeheel3r** [comment]
Hi,
Unfortunately there are no how-to's currently beyond [this short bit](https://github.com/OpenBoard-org/OpenBoard/wiki/Build-from-source#windows) in the build instructions.

The important part is that you'll need the msvc2010 compiler, as well as a Qt version that was built with that compiler (I recommend Qt 5.5 to be sure everything works).
I had started migrating to a more recent version of visual c++ but didn't manage to finish that, so that's why we're still stuck on this old version.

So the instructions would be, very roughly:
- Install MSVC 2010. The Qt wiki has a page on this: https://wiki.qt.io/How_to_setup_MSVC2010
- Install Qt 5.5 (msvc 2010 version)
- Build the 3rd party libraries freetype, quazip and xpdf. This can be done from Qt creator.
- Build OpenBoard


Let me know if you have any issues, perhaps I can help out. I've only had to setup the build environment once or twice, and that was a long time ago, so I don't remember the specifics to write a more detailed guide..

**Comment by mehmetaksakal** [comment]
So no instructions on setting up an IDE then?

**Comment by freeheel3r** [comment]
Qt Creator is the IDE; setting it up should be very straightforward as it auto-detects Qt and msvc versions. As long as those are installed correctly, it should be as easy as opening the projects (i.e. the .pro files of the 3rd party libraries, and of OpenBoard itself), and hitting build.

**Comment by mehmetaksakal** [comment]
Maybe it's because I'm using VS2017 but it's not happening for me.

**Comment by freeheel3r** [comment]
Yes, that'll definitely make things more complicated. Especially if you're using the 64-bit version, which causes issues with openssl (which is currently included as a 32-bit binary. Building it from source, so that we can use any compiler, is a pain)

**Comment by mehmetaksakal** [comment]
Ok, got it to work. Had to get rid of VS2017 which is a problem but I'll have to figure that one out.

After installing everything like described I got this very very weird error which took me a while to figure out. The build directory got set to some weird long javascript error. I don't have the exact thing anymore but it was something like:

`d:\openboard\OpenBoard\Error: Util.asciify("build-OpenBoard-Desktop_Qt_5_5_0_MSVC2010_32bit-Debug")": TypeError: Result of expression 'Util.asciify' [undefined] is not a function.`

This caused a path error to be displayed inside a javascript error, after much Googling I finally noticed all the build paths (the 3th party stuff too) was set wrong and after correcting those everything wen't just fine.

**Comment by frankhe2011** [comment]
@mehmetaksakal  You got it to work by use VS2010 instead of VS2017? I want use VS2015 or VS2017 but still didn't success. I don't want to switch to VS2010 because I want change the openboard to support Windows Multi-touch which needs at least VS2015.
