### ISSUE TITLE
[Bug] Graphic Tablet missing mouse pointer

### ISSUE THREAD

**Issue by DinoIsanovic** [OpenBoard-org/OpenBoard#1125]
When I put the stylus on my old Wacom PTZ-930 tablet the mouse cursor disappears, so I'm unable to track the position of my stylus on the screen. After the first use, I lose the ability to draw because my graphics tablet does not react. I have the same problem with the INKSCAPE program, while everything works without problems in the GIMP program. Of course, Linux itself recognizes the tablet and I can use a pen.

To Reproduce

Just put pen on the Graphic board. No help from settings under option "PEN".

Expected behavior
In older versions of 1.64 I could even see a cursor that showed me the position of my stylus on the screen.

Context

This part is MANDATORY (if not completed, the issue will be closed as incomplete)

reproducibility : systematic `
OpenBoard version :
bug happens with : 1.71 1.7.2 experimental`
bug doesn't happen with : 1.6.4 ` "1.70???"
didn't check :
OS :
bug happens with : Linux Ubuntu 24.04
bug doesn't happen with : Linux 23.10 with older version Open Booard, windows 10 1.64, 1.71
didn't check : macOS
Installation source : `Letsfindaway
Additional context

Additional context is very useful for an application like OpenBoard, that can work with a Wacom, an interactive whiteboard or a simple computer. Please provide any useful detail.

OS detailed version is MANDATORY (if not provided, the issue will be closed as incomplete).

For Linux users, simply copy/paste the result of the following command : lsb_release -d
For macOS users, go to "Apple > about this mac" and please provide (or take a screenshot and copy/paste it below) the OS version and device description, for example : "macOS Monterey 12.0.1 MacBook Pro (13 inches, M1, 2020)"
For Windows users, please go to Start > Parameters > System > About and please provide or take a screenshot and copy/paste it below) information given in the page.

Here's an example of what is expected :

OS(es) detailed version (for the ones you reproduced the bug on) :
Linux : Description:	Ubuntu 24.04 LTS
number and resolution of monitors : 2 mirored 1920x1080
if used, manufacturer and model of graphic tablet input device : Wacom PTZ-930

**Comment by letsfindaway** [comment]
> Just put pen on the Graphic board. No help from settings under option "PEN".

Did you try to set the size of the preview circle in the Preferences -> Pen to 1 px? The crosshair cursor is drawn by the operating system, while the preview circle is drawn by OpenBoard. So there might be a difference.

**Comment by DinoIsanovic** [comment]
THX,  1 pixel is OK.
That worked well, but for my old eyes, 2 pixels are much better :) 

Excellent program, fast response in case of problems, is there an option for 5 stars somewhere? In combination with a graphics tablet or a touch-sensitive laptop, it is much better than using an interactive whiteboard that will soon be on sale :)

Many thanks for this wonderful project.

**Comment by RickGxG** [comment]
Maybe this answer can help for those using OpenBoard and Wacom tablet in Ubuntu 22.04. Posted first: https://github.com/OpenBoard-org/OpenBoard/issues/514

I had a similar problem in Ubuntu 22.04 with OpenBoard 1.6.4 and a basic Wacom One tablet. It seems to be a problem with Qt and Wayland. I think the problem arises because OpenBoard is always in fullscreen. I have three workarounds:

1. Activate "Locate Pointer" in Ubuntu Settings > Accessibility. When the Ctrl key is pressed, the tablet pointer becomes visible for a moment. 
2. Select the "MultiScreen" option from the OpenBoard Menu (the little gear icon located below the close button). This action breaks the fullscreen mode and enables the tablet pointer visualization. Note: Some actions, like opening saved slides, might set OpenBoard back to fullscreen mode. 
3. Uninstall the old version and install OpenBoard 1.7.3 (in my case for Ubuntu 22.04, from [here](https://github.com/OpenBoard-org/OpenBoard/wiki/Downloads#other-platforms)). This version has the RunInWindow parameter, which must be set to true in OpenBoardUser.config file, normally located in the .local/share/OpenBoard/ folder. See OpenBoard [Configuration](https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration) and [Parameters](https://github.com/OpenBoard-org/OpenBoard/wiki/Parameters). 

I think the last procedure is the best, even though it doesn't fix the root cause.

**Comment by DinoIsanovic** [comment]
Solved with Manjaro (Arch) 👍
