### ISSUE TITLE
[Bug] Sporadic crash when deleting a newly added page

### ISSUE THREAD

**Issue by letsfindaway** [OpenBoard-org/OpenBoard#1139]
### Describe the bug

In some cases I experienced a crash when I deleted a page.

### To Reproduce

This did not crash it all the time, but often:

1. Create a document with two or three pages.
2. Go to the first page.
3. Open your file manager and drag a PDF document to the board. I used one with just a single page. The page is added to the end of the document. (side question: why not after the current page?)
4. On the thumbnails side bar, scroll to the newly added page and click the "delete" button on the thumbnail.
5. OpenBoard asks for user confirmation. Click "yes".
6. OpenBoard crashes.

#### Expected behavior
Page is deleted without crash

#### Actual behavior
See above

### Context
  - reproducibility : `not systematic`
  - OpenBoard version :
      - bug happens with : `dev`
      - didn't check : all others
  - OS : 
      - bug happens with : `Linux`
      - didn't check : all others
  - Installation source : `own build`
  - If you built OpenBoard from source, please provide the branch you're working on : `dev`
  
### Additional context

Stack trace at time of crash:
![grafik](https://github.com/user-attachments/assets/dec96611-ec77-46a6-aa18-1808428b9d95)

- While deleting the scene (frame13), OpenBoard also deletes the associated thumbnail at the document controller (frame 12).
- Note that the`UBDocumentContainer` in this frame is not the board controller, but the document controller. So we're talking about document thumbnails here.
- But the to-be-deleted element does not exist in the `mDocumentThumbs` list, so we get an "index out of range" exception.

**Comment by kaamui** [comment]
For me, to reproduce, systematically  :

1. launch OpenBoard
2. Go to Document Mode (now selected document is the same on Board and Document Modes)
3. Go back to Board Mode
4. drop a PDF in the board
5. delete one of the added pages 

=> crash

Several issues here : 
- adding a PDF this way triggers reloadThumbnails instead of just adding the new pages (after the current index as you said would be better indeed)
- the Documents thumbnails are not updated where it should if selected document is the same

Thank you for the tests and the feedback !
