### ISSUE TITLE
[Question] New Version (White boarders)

### ISSUE THREAD

**Issue by gabridomn** [OpenBoard-org/OpenBoard#1154]
Hi there,

In the latest version, it was added some kind of "white borders" to the sides of the board. Is it possible to remove it and maintain the "infinite style" of ALL black? 

Attached, an image indicating what I mean.

Thanks.
![problem](https://github.com/user-attachments/assets/360c6eb8-0712-4dad-b1dc-ab3d1d4845f6)

**Comment by amabilee** [comment]
Have you tried setting the background of the page to black?

Here is how you can do it:
1. On the top select the option `Backgrounds`
<img width="639" alt="Screenshot 2024-11-04 at 19 02 52" src="https://github.com/user-attachments/assets/53a1ada7-1478-43de-9a41-2679b533379e">

2. Then select the option full black
<img width="917" alt="Screenshot 2024-11-04 at 19 03 02" src="https://github.com/user-attachments/assets/987c8f58-8651-499f-9071-611b2fcdc5cc">

**Here is how it should look:**
<img width="1440" alt="Screenshot 2024-11-04 at 19 03 49" src="https://github.com/user-attachments/assets/22b0bb33-bb0f-401b-a571-f40147b3d7b9">

**Comment by amabilee** [comment]
Strange, I'm not having this problem.

I'm using the latest version for MacOS and as shown in the image in my previous message, the "infinite style" is still there...

**Comment by letsfindaway** [comment]
This problem is known and will be solved in the upcoming version 1.7.2 which is about to be released in a few days. See also #1014. Here you also find the circumstances when this happens - and how you can avoid it. The problem only occurs, when

- more than one monitor is connected,
- no monitor or more than one monitor is configured in the preferences,
- and single monitor mode was selected in the OpenBoard menu.

So the easiest way to avoid it i 1.7.1 is to open the preferences and enter the number of your single monitor there. This avoids the second conditions of the list above.

**Comment by gabridomn** [comment]
Oh, now I see @letsfindaway. I had to do a "downgrade" to avoid this problem. I'm looking forward to the next version to get this issue solved 👍 

Thank you so much for the support.
