### ISSUE TITLE
Multiple boards...

### ISSUE THREAD

**Issue by gabridomn** [OpenBoard-org/OpenBoard#1155]
Hey there,

Thank you guys for all of your support. I'd like to ask if it is possible to open multiple boards with the new version. I mean, in the previous versions, it was possible to open "multiple boards", which means we didn't have to select a new document or move to another page on the same one when we were explaining something.

I'll send a picture to explain better what I mean:

![problem 2](https://github.com/user-attachments/assets/c46ca00a-845c-4265-89ab-6759ac9f84a5)

Where I indicated in blue, it was possible to have "multiple files" opened. Now it's not. Could you help, please?

Thank you in advance.

**Comment by gabridomn** [comment]
Hello there,

I'm returning to the version 1.5.4, since it provides multiple boards opened at the same time. If you guys can solve this issue in the latest version (or the next), I'll appreciate a lot (👍 

Here's what it looks like from 1.5.4 (one of the features I'm missing):
![multiple boards](https://github.com/user-attachments/assets/94d34e79-98a9-4b66-89e0-63ad051c7c5b)


Thanks (>:

**Comment by kaamui** [comment]
Hi, It was removed because it is not an intended feature and not thread-safe. To reintroduce it properly, we would have to handle it differently, and it is not a priority at this time. 

Note that since 1.7.1, you can mark documents as favorites, and then switch from one to another quickly from the library in Board mode (in the favorites folder)
