### ISSUE TITLE
Change UI language / translation

### ISSUE THREAD

**Issue by petsuter** [OpenBoard-org/OpenBoard#116]
Is there a way to switch the UI language?

Looking at  the code, it seems there used to be a config setting `[App] PreferredLanguage=en", but it's ignored now:
https://github.com/OpenBoard-org/OpenBoard/blob/b228a5c972999b27d3e8a04b3ef44a59ff11c264/src/core/UBApplication.cpp#L205

Also it's possible to specify a command line argument `-lang en`. This still seems to work. Is that the recommended solution?

**Comment by freeheel3r** [comment]
I'm actually not really sure why this code was commented out. I'm fairly sure I've used it during development (after uncommenting it, and perhaps making some slight changes) so that I could test different languages. But given what is explained in that comment, I didn't want to re-activate this functionality without some very thorough testing. So it is likely to stay that way until someone can take the time to test this, and/or Geneva suddenly has lots of money to invest in low-priority tasks :)

But if the command line argument route works for you, that's great!

**Comment by nototbol** [comment]
I need change language, because auto setting is not always best solution. My system is in other language, than I need in app. But there is no option to change language.

**Comment by mooHUN** [comment]
Hi,

You can run it with parameters.
Right click on the Openboard icon (maybe you can make a copy)and choose the
properties, then Shorcut and find the target field.
At the end of the text u have to write: -lang <language code> . Example:
-lang de  -> deutsch , -lang hu  -> hungarian

I hope it will work for u.

Cheers,
Imre

nototbol <notifications@github.com> ezt írta (időpont: 2021. febr. 16., K,
7:16):

**Comment by Alhassan101** [comment]
Thanks a million
I've been struggling for a while, and eventually I could overcome it. Thanks again
