### ISSUE TITLE
[Bug] ctrl+i hotkey does not work anymore on v1.7.2

### ISSUE THREAD

**Issue by czyrichard** [OpenBoard-org/OpenBoard#1170]
### Describe the bug
ctrl+i hotkey does not work anymore on v1.7.2 on a win10 machine.

### To Reproduce

1. Press 'ctrl + i'
2. Nothing happens

#### Expected behavior
Ctrl + i should act normally like in previous versions

#### Actual behavior
Ctrl + i does not work

### Context
  - reproducibility : `systematic`
  - OpenBoard version :
      - bug happens with : `1.7.2`
  - OS : 
      - bug happens with : `Windows`
      - didn't check : `Linux` `macOS` 
  - Installation source : `OpenBoard download page`
  - number and resolution of monitors : `2`
  - OS(es) detailed version (for the ones you reproduced the bug on) 
    - Windows : `10`

**Comment by letsfindaway** [comment]
`Ctrl+I` and `Ctrl+O` shortcuts have been removed because `Ctrl+I` conflicted with the same shortcut now used for _Italic_ text in text boxes. Note: You can now also use `Ctrl+B` for Bold and `Ctrl+U` for Underline in text boxes.

`Ctrl++` and `Ctrl+-` do the same (Zoom in and Zoom out) and are also easy to remember, so please switch to those.

**Comment by kaamui** [comment]
If I remember well it has been replaced with ctrl+P for pen
