### ISSUE TITLE
[Bug] Significant delay between the cursor and where the writing appears (5mm or more).

### ISSUE THREAD

**Issue by Apuntesie2** [OpenBoard-org/OpenBoard#1177]
Describe el error
Cuando escribo con el lápiz o borro se produce un retraso importante entre el cursor y donde aparece lo escrito (5mm o más).
Gracias por esta pizarra tan maravillosa nos ayuda mucho a los profesores.
Para reproducir

Comportamiento esperado

Comportamiento real

Capturas de pantalla

Contexto
reproducibilidad:systematic
Versión OpenBoard:
El error ocurre con:1.7.2
No lo comprobé::1.7.1 1.7.0
El NO error ocurre con:1.6.4

Sistema operativo:
El error ocurre con: Windows
No lo comprobé: Linux macOS
Fuente de instalación: OpenBoard download page
Contexto adicional
Versión detallada del sistema operativo (en el que reprodujo el error)
Linux: 
Ventanas :11 actualización noviembre 
macOS: 
Número y resolución de monitores:1 (1920x1080) 
Si se utiliza, fabricante y modelo del dispositivo de entrada de tableta gráfica: wacom intuos pro m

**Comment by letsfindaway** [comment]
Sorry, I don't speak Spanish. Could you translate it to English? And probably add a screenshot, if it helps understanding your problem?

**Comment by Apuntesie2** [comment]
Sorry, I'll translate it with Google:
Error description:
When I write with the pencil or erase, there is a significant delay between the cursor and where what is written appears (5mm or more).
Thank you for this wonderful whiteboard, it helps us teachers a lot. 

Context
reproducibility:systematic
OpenBoard version:
The bug occurs with:1.7.2
I did not test::1.7.1 1.7.0
The bug does NOT occur with:1.6.4

OS:
The bug occurs with: Windows
I did not test: Linux macOS
Installation source: OpenBoard download page
Additional context
Detailed OS version (on which you reproduced the bug)
Linux:
Windows :11 November Update
macOS:
Number and resolution of monitors:1 (1920x1080)
If used, manufacturer and model of the graphics tablet input device: wacom intuos pro m

**Comment by letsfindaway** [comment]
That's actually a strange behavior. I did not observer that before and cannot reproduce it. Si I have some more questions:

- Is the offset always the same or does it vary?
- Is it in x direction or y direction or both?
- Is the offset different between the left and right side of the monitor or the top or bottom part?
- Or can you find any other rule about the size of the offset?
- Can you try to switch to the preview circle: Use a large pen diameter and go to Preferences->Pen and change the default threshold from 5px to 1px, so that the preview circle is displayed instead of the crosshair cursor. Do you also have the offset with the circle?
- Do you have a similar offset with the mouse?
