### ISSUE TITLE
PREFIX=/usr gets ignored?

### ISSUE THREAD

**Issue by probonopd** [OpenBoard-org/OpenBoard#146]
Using

```
qmake OpenBoard.pro CONFIG+=release PREFIX=/usr -spec linux-g++-64
make -j$(nproc)
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
```

I would expect to see `appdir/usr/share/openboard.desktop`, `appdir/usr/bin/OpenBoard`, etc.

But I don't see this structure; almost if `PREFIX=/usr` got ignored entirely.

**Comment by freeheel3r** [comment]
I do believe it's ignored, unfortunately.

It's been a while since I worked on this aspect of OpenBoard so I can't remember the details, but some (if not all) the paths are hard-coded, so simply changing the installation folder will result in the application not finding its configuration files, default library files, etc.

I'll see if I can find the relevant places where paths are hard-coded (and should be changed); I had never had the time to fix that myself but I believe it should be fairly easy to do.

**Comment by probonopd** [comment]
> To enable setting a prefix in this way, I think the QMake project file (OpenBoard.pro) would need to be modified. Right now it doesn't take this into account.

Thanks for checking. I would appreciate if you could change the pro file to allow for this to work. This would greatly help the production of an [AppImage](https://appimage.org/) which I am currently working on.

Thank you very much.

**Comment by kaamui** [comment]
Hi,

Did you manage to get it work ? let me know if I can close this one so anything related to your work can be found in the #147

**Comment by probonopd** [comment]
I am currently using manual workarounds:

https://github.com/probonopd/OpenBoard/blob/4fb8f37bd0610f07a6845200d7f3ba2ed315dbaf/.travis.yml#L43-L47
