### ISSUE TITLE
swf files appears like a white rectangle

### ISSUE THREAD

**Issue by fbarillon** [OpenBoard-org/OpenBoard#16]
On OpenBoard 1.3rc2, I can place .ogg, .mp3, .ogv, .mp4, .flv file, but if I try to drag n drop an .swf file, I just get a white rectangle.

This files were accepted on 1.2 and on Open-Sankore 2.5.1.

File example (zipped swf) : 
[cycle-de-l-eau.swf.zip](https://github.com/DIP-SEM/OpenBoard/files/189454/cycle-de-l-eau.swf.zip)

**Comment by freeheel3r** [comment]
Is this on Ubuntu 14.04? 
It works fine on my development environment (Linux Mint 17.3 with Cinnamon). Any problems are (most likely) due to the flash plugin installed.
Pipelight seems not to work (only a white rectangle is displayed). For example on KUbuntu 14.04, uninstalling pipelight and installing "flashplugin-installer" allows .swf files to be displayed again.
