### ISSUE TITLE
Dashed line / Alternative style of line

### ISSUE THREAD

**Issue by gagarine** [OpenBoard-org/OpenBoard#178]
Some teachers are drawing dashed line "by hand". Perhaps would be nice to be able to have dashed style. I was thinking it can be activated by selecting it or by **holding** control key like "alt" while drawing the line.

Another proposition would be to have two styles of line, the "main style" and the "alternative style". You will switch to the "alternative style" trough a button or a shortcut. Photoshop as a similar system to select the "main" and "background" color:
![image](https://user-images.githubusercontent.com/164074/48440755-062e4980-e78a-11e8-9f2d-b1195bf9fb66.png)

An example of what teachers draw (economics class):

![image](https://user-images.githubusercontent.com/164074/48440408-2578a700-e789-11e8-9dc7-30755bb378f9.png)

**Comment by kaamui** [comment]
Thank you for your feedback.

It could be a good idea but that would not be that simple to implement. Due to our very limited resources, we won't be able to access your request for the moment.

**Comment by bbreinbauer** [comment]
@kaamui : I would be interested in implementing such a feature and started to dig into the source code.
I played around with UBGraphicsPolygonItem class, which is used for drawing lines. From my pov it would be quite some work to implement dashed lines and so on with this class.
Therefore, I am thinking about creating a new class UBGraphicsLineItem (subclassing QGraphicsLineItem) and using the associated QPen for doing the dashed lines etc.

But before I really start, I would like to ask if there are any blocking issues with this idea. I do not have a full overview over the source code yet.
(Also I am wondering why the UBGraphicsPolygonItem class is used for lines. As far as I can see, the line is drawn with a polygon, but with deactivated outline and just a filling. Also, there is quite some calculation done in UBGeometryUtils::lineToPolygon to get the line. My assumption is, that this is because of the different startWidth and endWidth feature?)

**Comment by BruceMcF** [comment]
I will add that this is the main feature preventing me from adopting OpenBoard.

However, I will note that the dashed line I need is for the straight line tool ... it is to measure values from inside a graphical model down to the horizontal axis and across to the vertical axis. Students drawing graphical models by hand in face to face class exercise and open answer testing need a straightforward way to distinguish relations in the model and lines measuring results to axes. Open Board has good tools for drawing Demand and Supply models and labeling them, but not having a dashed line option for straight lines forces maintenance of two different set of PPTs for face to face and online class.

**Comment by ThomasLucky13** [comment]
@BruceMcF 
I made a dashed line implementation and also added a vector to OpenBoard. This is my PR: https://github.com/OpenBoard-org/OpenBoard/pull/714
Maybe it will be useful to you

**Comment by lbvn** [comment]
I downloaded the latest version 1.7.0, but it lacks support for dotted lines and vectors. Tell me, what am I doing wrong?
![image](https://github.com/OpenBoard-org/OpenBoard/assets/57588921/8f64652b-b0e0-4a70-a5c8-f5e3e8b1b9f9)
![image](https://github.com/OpenBoard-org/OpenBoard/assets/57588921/addd2293-43fc-420f-a444-98937a758ee2)

**Comment by temaps** [comment]
> I downloaded the latest version 1.7.0, but it lacks support for dotted lines and vectors. Tell me, what am I doing wrong?

Unfortunately, this PR has not been accepted.
https://github.com/OpenBoard-org/OpenBoard/pull/714#issuecomment-1533112260
But it is in the ROSA distribution
https://abf.io/import/OpenBoard/blob/rosa2023.1/0006-polygon_line_styles.patch
and in the free MOS distribution, which is used in schools:
https://os.mos.ru

**Comment by lbvn** [comment]
> Unfortunately, this PR has not been accepted.
> [#714 (comment)](https://github.com/OpenBoard-org/OpenBoard/pull/714#issuecomment-1533112260)
> But it is in the ROSA distribution
> https://abf.io/import/OpenBoard/blob/rosa2023.1/0006-polygon_line_styles.patch
> and in the free MOS distribution, which is used in schools:
> https://os.mos.ru

I don't need other distributions, but I need it on windows.
How do I deliver this feature, is there a patch maybe?

**Comment by ThomasLucky13** [comment]
> > Unfortunately, this PR has not been accepted.
> > [#714 (comment)](https://github.com/OpenBoard-org/OpenBoard/pull/714#issuecomment-1533112260)
> > But it is in the ROSA distribution
> > https://abf.io/import/OpenBoard/blob/rosa2023.1/0006-polygon_line_styles.patch
> > and in the free MOS distribution, which is used in schools:
> > https://os.mos.ru
> 
> I don't need other distributions, but I need it on windows. How do I deliver this feature, is there a patch maybe?

I can give you some patches. But when the OpenBoard version is changed they may not apply. The distributions mentioned above have support for these patches. Perhaps this will be more convenient in the future.


[changes for school.zip](https://github.com/OpenBoard-org/OpenBoard/files/15319904/changes.for.school.zip)
01 Patch (0001-toolbar-elements-changed.patch): It is needed for other patches. It show properties of only the selected tool (because now there can be a lot of them)
02 Patch (0002-polygon_line_styles.patch):  Line styles
03 Patch(0003-vector_tool.patch): Optional, if you need new tool - Vector.

**Comment by LevS9** [comment]
> > Unfortunately, this PR has not been accepted.
> > [#714 (comment)](https://github.com/OpenBoard-org/OpenBoard/pull/714#issuecomment-1533112260)
> > But it is in the ROSA distribution
> > https://abf.io/import/OpenBoard/blob/rosa2023.1/0006-polygon_line_styles.patch
> > and in the free MOS distribution, which is used in schools:
> > https://os.mos.ru
> 
> I don't need other distributions, but I need it on windows. How do I deliver this feature, is there a patch maybe?

Я работаю с OpenBoard не больше месяца, а на платформе windows три дня. Столкнулся с той же проблемой: нет инструмента  "вектор" и "пунктирная линия". Пробовал вначале "стираткой" делать нарисованную линию пунктирной, но надоело. Затем нашел эти патчи (0001-toolbar-elements-changed.patch; 0002-polygon_line_styles.patch; 0003-vector_tool.patch) и загорелся целью установить их,... Оказалось не так-то и просто "пропатчить" установленную OpenBoard... очень (неприемлемо!) хлопотно и положительный результат не гарантирован. 
Нащупал простой выход: я экспортирую файлик с нужными инструментами с OpenBoard под андроид, затем импортирую этот же файлик в свою OpenBoard на windows. В итоге имею эти объекты на своей доске, и копи-пастом размещаю их на нужных документах с последующими манипуляциями под нужное положение.
