### ISSUE TITLE
Thumbnail panel doesn't update upon changes

### ISSUE THREAD

**Issue by SamuelLongchamps** [OpenBoard-org/OpenBoard#19]
# Description

When the left panel (thumbnails of the document's pages) is opened, any modifications made to the page is not updated in the thumbnail until the user clicks on it.
## Reproduction steps
- Be in the board mode
- Open the left panel by clicking on the tab on the left of the window
- Acknowledge the thumbnail is blank
- Draw a strike using the pen tool on the board
## Expected result

The thumbnail is updated to show the drawn strike on the page
## Actual result

The thumbnail stays blank. Clicking on it updates it.
# Affecting

OS: Debian 8, Mac OS X 10.11.3, (Windows not tested)
Version: 1.3.0-rc2

**Comment by freeheel3r** [comment]
The thumbnails are updated upon page changes too, and whenever the document is saved. 
Since they are just a screenshot (saved as a jpg in the document's folder), it may be impractical to update them too often.

Do you have any ideas on how to address this?

I think there are a few different ways (feel free to complete this if I missed something) :

1. Keep the current system, and simply update the thumbnails much more often (e.g every X seconds)
2. Same, but instead of saving the thumbnail to disk every time, just generate the pixmap, set it, and wait until the document is saved to save the .jpg to disk
3. Instead of displaying a static Pixmap as thumbnail, implement them as QGraphicsViews, constantly mirroring the main view

The problem with 1) is that it would go against efforts that were made in the past to cut down on disk i/o (though it is not noticeable on most computers, in cases where the document's folder is on a network drive, OpenBoard would visibly slow down when saving stuff)

2) Might be the easiest "decent" solution to implement

3) would allow real-time updating in a cleaner way than 2), provided we keep the current system of saving the .jpg (which is useful e.g in the Documents panel, to avoid loading the whole document just to get the preview). A bit more work to implement than 2), though.

**Comment by SamuelLongchamps** [comment]
I haven't had the time to take a closer look at the scene's implementation, but IMO the third option would be the most flexible and clean way to do it. I don't know what would be the performance impact with regard to multimedia which require constant decoding such as video (especially for systems limited in resources and CPU). An option could be to have the scene objects provide a placeholder for the  thumbnail view (displaying an icon instead, for example).

Number 2 seems like a decent solution, but timewise it might be more future-proof to put the time in 3 right away.
