### ISSUE TITLE
Ukrainian does not follow gettext language code

### ISSUE THREAD

**Issue by glixx** [OpenBoard-org/OpenBoard#199]
Ukrainian must be OpenBoard_uk.ts instead of OpenBoard_ua.ts.

**Comment by kaamui** [comment]
Hello,

Thank you for reporting this. 

The ISO 639-1 defines Ukrainian code as 'uk' but the ISO-3166 defines it as 'ua', the code the translator used for this file. I'm not an expert on this subject and could easily change it if needed, but I don't know who is right. Can you explain me why it has to be uk instead of ua ?

Thank you.

**Comment by glixx** [comment]
ua is code of country, but not language, language is uk or uk_UA, but uk is enough.

**Comment by kaamui** [comment]
hello,

the change of the launguage code for the ukrainian translation's file extension has been added in the 1.5.3 release and is now available on Github
