### ISSUE TITLE
Add a partition as a default background of a document

### ISSUE THREAD

**Issue by snino64** [OpenBoard-org/OpenBoard#225]
¿Is it possible to add music score to set of papers background?
Thanks.

**Comment by kaamui** [comment]
Hello,

I think it is totally possible to add a partition as a background on a document, but the functionality of adding it as a default background (meaning it will be present on any new page) is not available in OpenBoard for the moment sadly. Just drop the desired image on a new page, set it as background (the third icon on the top left corner of the rubberband (see image below), and then use the duplicate icon on the thumbnails view instead of the "New Page" button to create a "new empty partition". 

![image](https://user-images.githubusercontent.com/11720903/57065573-27e4a400-6cca-11e9-8df1-2d5b98591348.png)

Hope it helps
