### ISSUE TITLE
Stroke recognizer

### ISSUE THREAD

**Issue by diegocaja** [OpenBoard-org/OpenBoard#234]
Most of the time I need vectors, circles an rectangles for my classes, for this reason,  I think something similar to the functionality "stroke recognizer" of "Xournal++" or "witeboard" would be nice.

Another possibility could be a stylus bar similar to "awwapp" or why not have a selection of arrows, circles or rectangles in the draw line option of the stylus as Xournal++ app.

I really would appreciate it, if this functionality was added to OpenBoard.

**Comment by diegocaja** [comment]
Something more spectacular could be the recognizer functionality of autodraw app. But I suppose, that implemented it is more difficult.

**Comment by npettiaux** [comment]
This could probably be implemented with the tools that run on gnulinux and have been developped for example for the https://remarkable.com tablet

**Comment by kaamui** [comment]
Hello,

Due to our limited resources, it might be really difficult to implement such a big feature. In Open-Sankoré, something simpler (tools to draw regular shapes) had been implemented but might be the good compromise, if it was decided to be ported. 

However, the core principle that led the creation of OpenBoard was to make simplicity back. At this time it was intentionally decided to not take such features, to keep OpenBoard simple. If it had to be implemented again, it would probably be something to enable in the configuration file.
