### ISSUE TITLE
compilation of the latest debian and ubuntu

### ISSUE THREAD

**Issue by npettiaux** [OpenBoard-org/OpenBoard#235]
It is important, at least in Belgium, that OpenBoard runs flawlessly on the most recent Debian and Ubuntu distributions, and be commercially maintained on such platforms. 

The fact that OpenBoard runs on all the main white interective boards and allows to prevent obsolescence is very important in this regards.

Oour team in Brussels is ready to help and contribute, but needs help.

Much thanks.

**Comment by kaamui** [comment]
Hello,

First of all thank you ! We are really pleased to hear that OpenBoard is used in Belgium. 

The officially supported platforms are Ubuntu (with a transition between 16.04 to 18.04 in progress), MacOS (10.9+) and Windows (7+).

For the other Linux distributions, you can [build OpenBoard from source](https://github.com/OpenBoard-org/OpenBoard/wiki/Build-from-source) or try the [Flatpack](https://github.com/OpenBoard-org/OpenBoard/issues/192), [AppImage](https://github.com/OpenBoard-org/OpenBoard/issues/147) approaches that the community is handling.

In Geneva schools, Kubuntu is deployed on Linux machines, so a major gnome issue like #67 is not a priority (but help is welcome 😄 !). 

An official Ubuntu 18 release is available, but swf support is broken (but it is the only known issue that prevent us to provide it as a production ready version, so if you don't use swf animations, you can use it). 

A huge work is actually made on making OpenBoard running on qt5.9.5 on each platform, with qt-webkit as a third dependency. When this task is achieved (and proven), Ubuntu 18 will become the officially supported platform (instead of 16).

**Comment by npettiaux** [comment]
Qt is used as a teaching platform for c++ (esi-bru.be). I'll ask the colleagues who teach the course to consider using openboard migration to Qt5.9.5 as a class exercice. I would love that the school be an active contributor to openboard

**Comment by JBBgameich** [comment]
Some patches are neccessary to get OpenBoard to compile against the system libraries of the latest debian in my experience. You can find my not yet upstreamed patches on [GitLab](https://gitlab.com/JBBgameich/OpenBoard/tree/dev).

**Comment by JefVR** [comment]
> Qt is used as a teaching platform for c++ (esi-bru.be). I'll ask the colleagues who teach the course to consider using openboard migration to Qt5.9.5 as a class exercice. I would love that the school be an active contributor to openboard

Hi Nicolas,

We have same issue in our school on Ubuntu 18.04; OpenBoard works fine with the mate desktop but the desktop mode is showing this refresh problem when we use the gnome desktop. do you know of a fix in the meantime?

Kind regards

Jef
