### ISSUE TITLE
Different backgrounds on each screen

### ISSUE THREAD

**Issue by diegocaja** [OpenBoard-org/OpenBoard#237]
I like to use the white checkered background in my computer to have a better organization of my notes handwritten.  But at the same time, I would like to have a white background on another screen, when, I am using the multi-screen option. 

Could be this option implemented? Thanks.

**Comment by kaamui** [comment]
Hello,

Thank you for this idea. However, due to our limited resources, we cannot prioritize on this feature request. 

In my opinion, this would ask some brainstorming and some days to develop, because of the actual behavior of the secondary screens. You would have to think of what to do with 3 or 4 secondary screens and how to give the user the ability to change the background style on each.

 OpenBoard is open-source, so if you or anybody has some skills in programming, it could be interesting to see such features in the pull requests.
