### ISSUE TITLE
Desktop mode: Automatically release the keyboard focus when Selection icon is clicked

### ISSUE THREAD

**Issue by jondo** [OpenBoard-org/OpenBoard#246]
Quoting my corresponding [forum thread](openboard.ch/forum/viewtopic.php?f=8&t=2564&p=3296):

> I would like to use OpenBoard to present an application. For this, I would use the Desktop mode, and I would need a fast way to switch between "laser pointer" and keyboard interaction with my application.
> 
> Is this possible, or do I have to click the control panel (and the application to set the input focus) at each switch?
> Best would be to "route" the keyboard input to my app while the laser pointer is still active.
>
>Maybe OpenBoard could automatically drop/release the keyboard focus, when the Selection icon (arrow symbol) is clicked, such that the focus automatically returns to the last recently used application?

**Comment by kaamui** [comment]
hello,

thank you for your feedback. 

Your request is really specific. Due to our limited resources, this request will not be prioritized. If you have some skills in development, or if you know somebody that could help you, you might consider build openboard from sources, and try to implement it. 

You could then submit it as a pull request, so we can validate it to include it in the master.
