### ISSUE TITLE
2019/2020 Roadmap

### ISSUE THREAD

**Issue by kaamui** [OpenBoard-org/OpenBoard#253]
Hello everyone,

I wanted to give you a small update on the current status of OpenBoard's development. Recently, we were working at porting OpenBoard to qt 5.9, on the three supported platforms, with qtwebkit as a third dependency. 

Porting OpenBoard to Qt 5.9 implied some good news : 

- Because Qt 5.9 apps can be built with msvc 2017 and mscv 2017 supports C++11, we can now use C++11 based libraries on the three platforms, so ffmpeg can now be used on Windows too
- OpenBoard can now be built in 64bit on Windows
- qtwebkit latest builds provide a way more up-to-date support around web-oriented technologies (WebGL, HTML5, CSS features, etc)

These changes are really important, but it is not a small task. While making OpenBoard work with Qt5.9 fixed some issues, it created new ones. At the same time, it has been decided that Ubuntu 20.04 will be deployed in our Linux machines (in Geneva schools), so OpenBoard will have to support it. 

Because of the last point, the team and I think that it became more interesting to port OpenBoard directly to the latest version of Qt (5.12 or 5.13). 

We hope to find the time to replace xpdf by libpoppler  (on the three platforms) in the same time.

In parallel, we are preparing the last version that will be based on Qt5.5, OpenBoard 1.5.4. This release will only contain bugfixes (some by the community!) and small features, but will improve the user experience quite a bit.

We know that a lot of features (and some really good ideas) are requested, and we apologize for not being able to satisfy everyone's desire, but as you may read so (too?) many times, we have very limited resources.

Thank you, a lot, for the support you send us (from all around the world) and the feedback you take time to give.

**Comment by ttrindade80** [comment]
Hello, I am a professor at www.ifb.edu.br, in Brazil, and I really liked of the OpenBoard. I work with gentoo, and I tryed to compile OpenBoard to gentoo linux, but the depency of QtWebKit make it complicated. I verified that the code use QGraphicWebView and QWebPage::SetPalette that are not supported by the QtWebEngine.

I understand that you are working hard to provide OpenBoard on all three platforms, windows, mac and linux, I also understand that Ubuntu is a widely used linux distribution. My point is that I use several tools that are best used in Gentoo. So my questions are:
1) What is the forecast for OpenBoard for Qt 5.12 or 5.9 to be available?
2) Could I get a version of the code that is being developed for Qt 5.9? This type of programming is not very much of my field, but I know C ++ very well and have worked with other linux distributions in the past, so I am willing to help you out.

I'm interested in using OpenBoard together with a wacom tablet and maybe integrate some handwriting recognition tool, since I've seen that there are some developed with Qt.

I am also interested in geometric figures, trigonometric functions and electrical circuit components recognition systems. I believe that using a tablet and a tool like OpenBoard can help a lot in electronics and electrical circuit classes.

**Comment by maehne** [comment]
> 2. Could I get a version of the code that is being developed for Qt 5.9? This type of programming is not very much of my field, but I know C ++ very well and have worked with other linux distributions in the past, so I am willing to help you out.

Development seems to happen in the [dev-qt5.1x](https://github.com/OpenBoard-org/OpenBoard/tree/dev-qt5.1x) branch.

**Comment by kaamui** [comment]
Hello,

> * What is the forecast for OpenBoard for Qt 5.12 or 5.9 to be available?

I don't know gentoo but using Qt 5.13, you could probably use nightly builds provided [here](http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/), qtwebkit Alpha 4 is going to be released soon and will probably provide qt 5.12 binaries too. 

> * Could I get a version of the code that is being developed for Qt 5.9? This type of programming is not very much of my field, but I know C ++ very well and have worked with other linux distributions in the past, so I am willing to help you out.

It's pretty much the same code. You can try with the dev-qt5.1.x branch (both on OpenBoard and OpenBoard-ThirdParty), where the work of @JBBgameich has been merged regarding libpoppler on linux.

On linux, the remaining issues are related to the font dialog no longer working (UBGraphicsTextItem and UBGraphicsItemDelegate classes) and the desktop mode (not updating on Gnome, but OK on KDE)

I'm also working at writing some help to build OpenBoard on every supported platforms, it could help you but it is still WIP. here's the readme for Ubuntu

[readme-openboard-qt5.13-master.zip](https://github.com/OpenBoard-org/OpenBoard/files/3778305/readme-openboard-qt5.13-master.zip)

Hope it will help

**Comment by JBBgameich** [comment]
Hi @kaamui !
It's great to see that you are working on some modernization of the codebase and updating to newer libraries.

I spent quite some time working on similar topics on the openboard codebase. Some of this work is used for the openboard flatpak, which runs on Qt 5.13 as of now. But there are a few other experiments currently not in use, like a port to cmake which I hope would allow to drop some workarounds and finally make finding dependencies easier. Since Qt is moving away from qmake in favor of cmake for their own build system, I expect cmake to become the better supported one in the Qt6 era. While switching the build system is no requirement for Qt6 and not really needed for linux packaging either, it would be really important to port away from deprecated Qt APIs, to make sure porting to Qt6, which is supposed to be released in about a year will not be such a large amount of work. If I remember correctly I already submitted one pull request starting to do this work.

Let me know if any of my existing work on gitlab.com/jbbgameich/openboard is useful to you for porting to newer Ubuntu releases, and I'd be happy if some of my linux integration work could be upstreamed to reduce the amount of patches required for the flatpak.

Thanks for your continuous work in this great project!

**Comment by kaamui** [comment]
> But there are a few other experiments currently not in use, like a port to cmake which I hope would allow to drop some workarounds and finally make finding dependencies easier. Since Qt is moving away from qmake in favor of cmake for their own build system, I expect cmake to become the better supported one in the Qt6 era. 

Porting to cmake will not be a priority at all, always for the same reasons. Personnally, I'm not quite a fan of it, because I think it is not really accessible, for begginers. I like to keep things simple and as accessible as it can be. Cmake is not simple to manipulate, (neither on linux, osx or windows, on large projects). 

Regarding that, the main priority is to make Building OpenBoard from source the easiest possible. Actually, by a lack of documentation, on each platform, it is not as simple as it could, and I suspect this to reduce the number of active contributors. I don't want to loose some potential contributor because he or she had issues installing and/or configuring cmake. 

> If I remember correctly I already submitted one pull request starting to do this work.

Yep, I keep it in mind since you submitted it. I'll probably add it soon. My focus is actually on releasing OpenBoard 1.5.4 and fixing font dialog issues and gnome desktop for the "1.6.0" release.

> EDIT 1: Also using CI for this project would probably help to see if the code breaks on specific Ubuntu versions. For my work on OpenBoard i use the following pipeline: https://gitlab.com/JBBgameich/OpenBoard/pipelines/92083423. It is also possible to use GitLab CI with github btw.
> 

Yes, I want it too and I already argued for that on my side. Work is been done so I can have more time on OpenBoard to make things like that happen.

> Let me know if any of my existing work on https://gitlab.com/jbbgameich/openboard is useful to you for porting to newer Ubuntu releases, and I'd be happy if some of my linux integration work could be upstreamed to reduce the amount of patches required for the flatpak.

Ok I'll try to look at it.

Thank you for your active contributing.

**Comment by prunkdump** [comment]
Hello !

I'm interested to make OpenBoard working on Debian 10. So I can give help to upgrade the code to make it working with newer libraries.

-> I have successfully built OpenBoard on Debian10 without using any third party libraries (Using Qt5.11).
-> To do this I have ported the xpdf code to poppler-qt5.

I would like to give you the code but there is a bug somewhere else that prevent me to finish the work completely.

In many place in the code the rendering DPI is computed like this :
```
QDesktopWidget* desktop = UBApplication::desktop();
int dpi = (desktop->physicalDpiX() + desktop->physicalDpiY()) / 2;
```

But on my platform, physicalDpi return always 0 on desktop widgets. So the physical dpi is wrong everywhere in the code.

Is anyone have an idea how to update these code lines ? And why they don't works ?

Regards,

Baptiste.

**Comment by JBBgameich** [comment]
@prunkdump  Unfortunately I can't help you with the dpi issue right now, but I'd like to ask you to base your work on top of my repository on gitlab mentioned above to avoid duplication of work. There I already added compatibility with up to debian sid without third party libraries. I'm slowly working on upstreaming those changes, for example the poppler port has already landed.

Kind regards, Jonah

**Comment by prunkdump** [comment]
Thanks Jonah for your help.

Did the PDF importer works on your platform ? I have just tested your code and the pdf files are not displayed. I think this is also due to the "physicalDpi" problem.

Or maybe my problem is Gnome, or virtualized environment related.

Regards,

Baptiste.

**Comment by JBBgameich** [comment]
Did you port to th Qt5 API? In that case please try to upstream the changes to the openboard branch thay already uses plopper (don't know which right now).

**Comment by prunkdump** [comment]
Yes I have port the code using the [poppler Qt5 API](https://poppler.freedesktop.org/api/qt5/).

But I can't pull request for now due to the desktop->physicalDpiX() problem. I'm investigating...

**Comment by JBBgameich** [comment]
If you want I can test your code on a device that doesn't require scaling and works with the current poppler implementation.

**Comment by prunkdump** [comment]
I have uploaded the poppler-qt5 code on the **dev-qt5.1x** branch [here](https://github.com/prunkdump/OpenBoard)

The modified files are :
-> src/pdf/XPDFRenderer.cpp
-> src/pdf/XPDFRenderer.h

Read the "BUG" comments. And check if 
`this->dpiForRendering`
Return 0.0 on your platform (it must not).

To compile don't forget to install "libpoppler-qt5-dev" and to add "-lpoppler-qt5" to your LIBS.

Thanks !

Baptiste.

**Comment by JBBgameich** [comment]
dpiForRendering returns `96` on my laptop, but the resulting rendering is waay to small (the image is only visible in the top left corner of the page).

Btw, for finding poppler-qt5 properly use 
```
CONFIG += link_pkgconfig
PKGCONFIG += poppler-qt5
```

**Comment by prunkdump** [comment]
JBBgameich I would like to talk with you about the OpenBoard development but I can't find your email.

Can you contact me with the email on my GitHub account ?
https://github.com/prunkdump

Regards,
Baptiste.

**Comment by kaamui** [comment]
A snapshot of the current progress on this porting can be found [here](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a)

**Comment by kaamui** [comment]
A package for Ubuntu 20.04 with up-to-date dependencies is available [here](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a1)

**Comment by Gvf63** [comment]
On Xubuntu 20.04 is required qt5dxcb-plugin also
