### ISSUE TITLE
Openboard build.sh fails on raspbian

### ISSUE THREAD

**Issue by KailashKS** [OpenBoard-org/OpenBoard#260]
./build.sh either fails or hangs while installing openboard. I created a swap file and have a good sd card. Is there any way to install openboard on raspbian

**Comment by JBBgameich** [comment]
In case this aims at installing on the raspberry pi hardware rather than necessarily on raspbian, you can use the flatpak as long as you use a distribution that runs in 64bit mode (arm64) instead of armhf like raspbian.

https://flathub.org/apps/details/ch.openboard.OpenBoard

If this doesn't work for you, you need to use my patched version of openboard, since you can not rely on thirdParty prebuilts as needed for the official repository (the prebuilts are only available for intel 64bit).
https://gitlab.com/JBBgameich/OpenBoard/tree/dev
You can use the `ci_scripts` to somewhat automate the build process. https://gitlab.com/JBBgameich/OpenBoard/tree/dev/ci_scripts
