### ISSUE TITLE
Panel size on UHD screen

### ISSUE THREAD

**Issue by teacheratwork** [OpenBoard-org/OpenBoard#275]
Hi guys! I have microscopic panels on win 10 and uhd screen resolution. Any suggestion on how can I fix this?

**Comment by kaamui** [comment]
Hello,

Can you describe more your problem, and give some info on your specs ?

**Comment by teacheratwork** [comment]
I am working on a 3840 x 2160 resolution screen (14''). The laptop is a
Lenovo Yoga C940 with win 10 Home. I haven't figured out yet how to make
OpenBoard ux scale correctly (if it's possible to do it).
Any help would be appreciated, thank you!

Il giorno lun 23 mar 2020 alle ore 09:42 kaamui <notifications@github.com>
ha scritto:

**Comment by teacheratwork** [comment]
Sorry, I forgot to attach a screenshot of the tiny panels

[image: 2020-03-23 09_53_17-OpenBoard.png]

Il giorno lun 23 mar 2020 alle ore 09:52 Samuele Macciò <
samuele.maccio@gmail.com> ha scritto:

**Comment by kaamui** [comment]
Hello,

Someone already reported an issue with 4k screens if I remember well. I think we don't handle resolutions this high correctly at this time. Do you still have the issue with a standard resolution ?

Due to our limited resources, it might be difficult to fix this one in priority (also it doesn't correspond to a need for our schools, so it will not e prioritize).

I accept PRs though :)

**Comment by teacheratwork** [comment]
No, I'm still using it shifting to a FullHD resolution. I understand this
is not a priority and I thank you for the great job you have done!

SM

Il giorno lun 23 mar 2020 alle ore 10:37 kaamui <notifications@github.com>
ha scritto:

**Comment by Amr-Ibra** [comment]
Maybe please keep this issue open as long as it's not fixed in the code, so that people can easily find it to either upvote it or for contributors if they want to contribute code.

#280 is a duplicate issue.
