### ISSUE TITLE
How to build openboard  using QT5.14 on windows10

### ISSUE THREAD

**Issue by bishangshuo** [OpenBoard-org/OpenBoard#277]
Please someone would like to give me a guide or link to compile openboard on windows10 with qt 5.14, Thanks so much.

**Comment by kaamui** [comment]
Hello,

I'll try to update the wiki on how to compile OpenBoard from source. 

Quickly for qt 5.14, you need to : 
* go to the dev-qt5.1x branch both on OpenBoard and OpenBoard-ThirdParty
* install Qt 5.14
* install qtwebkit alpha 4 (alpha 3 if qt5.13)
* resolve the issue with libpoppler (what I'm facing right now) or rollback to XPDF
* compile
* copy/paste the dlls required on your build directory

**Comment by bishangshuo** [comment]
> Hello,
> 
> I'll try to update the wiki on how to compile OpenBoard from source.
> 
> Quickly for qt 5.14, you need to :
> 
> * go to the dev-qt5.1x branch both on OpenBoard and OpenBoard-ThirdParty
> * install Qt 5.14
> * install qtwebkit alpha 4 (alpha 3 if qt5.13)
> * resolve the issue with libpoppler (what I'm facing right now) or rollback to XPDF
> * compile
> * copy/paste the dlls required on your build directory

great jobs,
I can hardly wait.

**Comment by bishangshuo** [comment]
@kaamui By the way, Are you trying to compile Openboard with MSVC2017 compiler right now?
Please tell me if it works or not, Thank you so much.

**Comment by bishangshuo** [comment]
@kaamui I had carried out the build of Openboard, with MSVC2017 on windows10, fellow the step by step guidelines you told me. Thinks!

One more question: Where do  I start to learn the source code? Is there any documentation to introduce the system's construction?  I just wanna learn...

**Comment by fsckawk** [comment]
@bishangshuo so, you managed to compile Openboard, great!
I'd like to ask you a favour. I've changed just a line of Openboard code in order to have it running on a window, instead of fullscreen. I've compiled it on CentOS 7 Linux without problem, but I haven't Windows systems, let alone MSVC.
Would you be interested in compiling a binary with my minimal patch? Thanks in advance!

**Comment by bishangshuo** [comment]
> @bishangshuo so, you managed to compile Openboard, great!
> I'd like to ask you a favour. I've changed just a line of Openboard code in order to have it running on a window, instead of fullscreen. I've compiled it on CentOS 7 Linux without problem, but I haven't Windows systems, let alone MSVC.
> Would you be interested in compiling a binary with my minimal patch? Thanks in advance!

Sorry I am so late to reply, I will try it once There is time free for me~

**Comment by fsckawk** [comment]
Thanks a lot!
The only change is in line 281 from file src/core/UBApplication.cpp (OpenBoard 1.5.4 sources). Just change FramelessWindowHint to WindowCloseButtonHint.

The resulting line reads:
mainWindow = new UBMainWindow(0, Qt::WindowCloseButtonHint); // deleted     by application destructor

**Comment by fsckawk** [comment]
https://twitter.com/fsck_awk/status/1247112433728204801

**Comment by fsckawk** [comment]
Ok, I could setup a virtual machine with Windows 7 64 bits, community version of MSVC and compile OpenBoard. In windows you shoud chage also 
src/frameworks/UBPlatformUtils_win.cpp at line 459 and replace "showFullScreen" with "showNormal" in UBPlatformUtils::showFullScreen
The resulting line reads:
pWidget->showNormal(); /* SPD */

**Comment by fsckawk** [comment]
Finally, I'm able to announce the succesful compilation and deploy of Windows, macOS and GNU/Linux of OpenBoard-in-a-Window:

http://webdiis.unizar.es/~spd/openboard/

**Comment by kaamui** [comment]
Hello guys and sorry for the late reply: I try to answer every week but I hadn't seen your replies since my last one.

> @kaamui I had carried out the build of Openboard, with MSVC2017 on windows10, fellow the step by step guidelines you told me. Thinks!
> 
> One more question: Where do I start to learn the source code? Is there any documentation to introduce the system's construction? I just wanna learn...

No documentation to learn the source code. To answer quickly, the application is structured around a UBDesktopController for the Desktop Mode, a UBBoardController for the board mode, and a DocumentController for the documents mode. 

> Finally, I'm able to announce the succesful compilation and deploy of Windows, macOS and GNU/Linux of OpenBoard-in-a-Window:
> 
> http://webdiis.unizar.es/~spd/openboard/

Hello, 

Could you make a PR of your work ? Did you make it optionnal so we can choose to be in window mode or fullscreen mode in the preferencesCotnroller ? How does the desktop mode behaves ?

**Comment by fsckawk** [comment]
Hello, @kaamui
No, I didn't made a PR for two reasons:

First, this is a quick and dirty hack to make it work windowed, as requested from coworkers who needed it to use OpenBoard with "window sharing" videoconference software. I'd like to make it optional, but that will require a little more work.

Second, OpenBoard team have made clear that they don't want such a feature.
https://openboard.ch/forum/viewtopic.php?t=931
I could make a fork, but that would be a little excessive, I think.

About the "desktop mode", seems to run properly. Here you are a screenshot from GNU/Linux CentOS 7 (running the Motif window manager instead of the usual Gnome).
[Screenshot](http://webdiis.unizar.es/u/spd/openboard/oblinuxdesktop.jpg)

**Comment by kaamui** [comment]
If you make a PR with it being optional (with a parameter in the preferences and the config file), that is disabled by default, I don't see why we would not accept such a thing.

**Comment by fsckawk** [comment]
You're right, I'll do that.

**Comment by fcmoses** [comment]
@kaamui , @bishangshuo , @fsckawk I'm working with Haiti Futur which has over 500 Open Sankoré systems in Haiti.  To be working on live code, we wish to switch to OpenBoard, but it doesn't translate their ubz files correctly and may have other incompatibilities.  I'm having problems building OpenBoard from source on Windows 10 which I want to do for debugging purposes and to be able to help out with OpenBoard in general.  I'm also interested in eradicating the need for Flash handling in OpenBoard since Flash is nearly dead.  I'm willing to pay back by working on OpenBoard if one or more of you could do some hand holding and help me build a development environment.  Just being able to build OpenBoard would do.  I've gotten part way, but have trouble with xpdf and the final build. 

While I've done some C++ programming (3 or 4 years worth about 25 years ago), my main expertise is C# using VS 2017 and 2019.  Over all, I have about 40 years of experience as a developer, much of which was building publishing systems.

**Comment by maehne** [comment]
@fcmoses: Have you checked out the dev-qt5.1x branch? It should use libpoppler (which is available in MSYS2) instead of xpdf.

**Comment by fsckawk** [comment]
I've written some compiling guides for serveral environments here:
http://webdiis.unizar.es/~spd/openboard/

**Comment by kaamui** [comment]
@maehne Did you find a way to build on Windows using a proper build of libpoppler ?

Hello @fcmoses 

I'm thinking of making a rollback from poppler to xpdf on Windows, because I can't manage to make this dependency work on this OS.

**Comment by williamsdom** [comment]
buenas tardes, he probado en windows 10 y no me gunciona openboard, que puedo hacer. williamsdom@gmail.com

**Comment by fsckawk** [comment]
> buenas tardes, he probado en windows 10 y no me gunciona openboard, que puedo hacer. [williamsdom@gmail.com](mailto:williamsdom@gmail.com)

La versión compilada que hay en mi página me han confirmado que funciona en Windows 10. ¿Qué error te da?
