### ISSUE TITLE
Multi(>2)screen features (selection of draw-screen, selection of display screen, etc.)

### ISSUE THREAD

**Issue by BFH-ktt1** [OpenBoard-org/OpenBoard#304]
I really love openboard and using it already for quite some time, now during the COVID confinement I also use it to record my lectures, and with this I have some experience of things that would be great to have in openboard with respect to multiple screens (read more than 2).
Let me first go into the details of my setup to give some background information:
I use a setup with up to 4 screens connected, 2 Hi-res, 1 Wacom Cintiq 16, and a ASUS zenscreen (medium resolution to be able to record my sessions). I use Ubuntu 19.10 and Openboard 1.5.4 through flathub.
The "anoying" part I am facing is that:
1) Each time I start recording I have to change my main display to my Wacom device.
2) In multi screen session openboard will "occupy" all screens where the main-screen is correct, the secondary display shows the current slide and all other screens show slide-1.
3) So now and than when I show my desktop, it will not take the image of the primary screen, but any of the other 3 which gives quite some nice effects.

Hence it would be nice if in openboard we could configure:
1) Which of the screens is the main-screen
2) Which of the screens is the "presentation screen".

and leave all the other screens untouched.
I would be willing to work on this, but I have no idea for the moment where to find the code-base in the sources that handle this part of the program.

**Comment by kaamui** [comment]
hello,

thanks for reporting this and for your motivation. I think it will not be really simple to do so but It could be really interesting to have such a good feature. 

I think most of what you'll have to touch is on the core section, like in the UBDisplayManager and UBApplicationController classes

Good luck

**Comment by ep12** [comment]
Hi there,
we use OpenBoard in our lecture hall. Previously, we had just a wacom screen and two projectors. We now want to add a screen for the lecturer to have their notes on (or other uses). It is strictly necessary that OpenBoard does not start to display anything on that screen. After all, that sounds very similar.

I started to hack on that problem and I'm almost halfway through, I'd say. It is possible to disable screens, but for testing purposes that is hard-coded into the patch. It was necessary to almost completely rewrite UBDisplayManager to have a better level of abstraction instead of storing indices of screens. A side effect is that UBDisplayManager should now be qt6-compatible (it previously used `qApp->desktop()` and other deprecated stuff that will not be available in qt6 anymore).
After a bit of playing around with it I think this doing what it is supposed to do. The next step is to make it configurable (via the config file) and then check other screen configurations.

If anyone wants to have a look at it, the branch I'm working on is `configurable_screens_t2_1.7-dev` over at [ep12/OpenBoard](https://www.github.com/ep12/OpenBoard). It is quite a git history mess, but when I'm done I'll squash those commits and add a proper commit message...

**Comment by letsfindaway** [comment]
I think OpenBoard was initially designed for one or two monitors having in mind a typical class room situation with a desktop monitor for the teacher and a projector or large display for the students. The handling of more than two displays displaying the previous pages or a blank screen (see e.g. explanation at https://github.com/OpenBoard-org/OpenBoard/issues/395#issuecomment-727822447 seems to me a feature without much practical use, especially as the distribution amongst the screens cannot be configured, as you described.

So it seems to me very reasonable to rethink the monitor configuration of OpenBoard. But instead of having a completely flexible screen management, I would like to ask what is really needed by users in actual use cases of OpenBoard. OpenBoard development always has user's needs in the focus. Instead of (as we call it in Germany) "featureitis" implementing every feature somebody has in his/her mind, it focuses on actual use cases and user's needs, and to make those easily accessible.

In my opinion (but that just mine - and I do not even use OpenBoard in a class room - there is no need to occupy more than two displays: one for the teacher and one for the students. Displaying previous pages on other screens does not help much in practical use. But it is absolutely necessary to have better control over which displays are used for what purpose. I like to see other people's opinions here, and especially their actual use cases!

If you want to discuss your work on that here I would recommend to create a pull request for it. It is then much more visible here and people can discuss about the topic as well as about the code changes you did.

**Comment by letsfindaway** [comment]
With OpenBoard 1.7.x the preferences allow to specify the used screens. So I'm closing this issue here as completed.
