### ISSUE TITLE
There's no way in desktop mode to select an object

### ISSUE THREAD

**Issue by ghost** [OpenBoard-org/OpenBoard#311]
Hi,

When in desktop mode, I was unable to find a way to select (in order to move or delete it) any stroke previously drawn. 

Regards.

OpenBoard 1.5.4 tested on Win10-1909

**Comment by kaamui** [comment]
Hello,

Indeed. The Desktop Mode is mainly deisgned to let the user interact with other apps with Openboard as an overlay. There is no persistence of what is done in the desktop scene, nor the ability to move drawn items or select/group them. You can erase them using the eraser selector (or by maintain the click on the eraser selector and choose the "erase all" action)

**Comment by habruening** [comment]
I think, the difficulty is not to achieve that the (lets call it) desktop selector is designed to interact through the transparent scene. This already works with your masking mechanism. But we would also have to implement that the desktop selector interacts through the non-transparent parts of the scene. I am trying to implement this but I still failing, and I am not even able to develop a simple Qt proof of concept. I don't know in general if it is possible to click through a window.
In case we could achieve this, am I right that the masking mechanism would be no longer required? I tried to uncoment this completely. The result is still working for the drawing functions. Only the desktop selector does not work any more.
I think, this will be hard to implement because it is very dependent to the operating system windowing system.
An alternative could be that in the moment when the user clicks on the desktop selector, the scene disappears and comes back when the user clicks on the drawing functions or the cursor selector. So this will be a compromise but at least should work reliably on all systems.

**Comment by habruening** [comment]
I made experiments and made the desktop palette a top level window (with no parent) that is always in foreground. Then the masking mechanism is not required any more. The only thing that will not work is that you can click through the annotations to work with the desktop. You can either have control over the desktop without seeing the annotations or you see the annotations but have no control over the desktop. It is different from what we have now, but it is not so bad.
