### ISSUE TITLE
How do I scale general icons and text?

### ISSUE THREAD

**Issue by eklipse18** [OpenBoard-org/OpenBoard#425]
I am running Ubuntu 20.04 on my laptop and I have enabled fractional scaling, but due to the fractional scaling everything usually becomes tiny in apps. I have seen the css file in `/opt/openboard/etc` directory, but I am not able to figure out how to increase the size. I have tried adding
```css
* {
    font-size: 2em;
}
```
But it does not work. Is it even possible to increase the size of all the texts (and icons) ?

**Comment by kaamui** [comment]
Hello,

I don't know. Here's [the documentation on Qt stylesheet](https://doc.qt.io/qt-5/stylesheet-reference.html). To be sure you're actually modifying the good file, try to identify something easy to find on the app and add something like `border : 5px solid red` to see if you successfully alter it. Then search for what to modify to achieve what you want to do. 

I don't know if icon and icons' text can be altered this way. If not, it could be necessary to search in .ui files like mainwindow.ui

I've no time for that actually, but I'll try to look at by the end of this year, because we already have an issue in very high resolution displays.
