### ISSUE TITLE
Portable installation for Windows 10

### ISSUE THREAD

**Issue by DJuego** [OpenBoard-org/OpenBoard#432]
I just discovered OpenBoard. A really interesting software. Thank you very much for the time and effort dedicated to it. 
I have a request: Would it be possible to offer OpenBoard in "portable format" (i.e. no installation required)? At least for Windows.

Thank you!

DJuego

**Comment by AndhikaWB** [comment]
I just made one if you would like to test: https://portableapps.com/node/63423

It's unofficial though since I'm not directly afiliated with the team.

**Comment by DJuego** [comment]
Thank you for this, @AndhikaWB . You are very welcome.  I am now experimenting with the beta version (OpenBoard_1.6.1-a1102) but it is nice to have a portable version of the latest stable release. 

 Hopefully consideration will be given to including a .zip file with the binaries for future releases, no installation required.

DJuego

**Comment by AndhikaWB** [comment]
You can use Universal Extractor to extract files from (almost) every installers, there are many variants since the official one was discontinued but I'm using this [one](https://github.com/Bioruebe/UniExtract2), portable and still maintained. May trigger antivirus warning though.

**Comment by kaamui** [comment]
Hello,

I'm not sure everything would work as expected, especially on Windows. OpenBoard has dependencies like Visual C++ Redistribuable dlls or LAV Filters dlls to be installed and correctly registered. It might seem to work because you have vc_redist installed for other reasons, for example, but not sure it would be working perfectly on a fresh Windows Install, especially for the registry entries LAV_Filter needs to add to make the system aware of its dlls location. 

And even if I'm wrong, we clearly don't have time for another packaging to handle ^^. Sorry.

**Comment by DJuego** [comment]
Thanks for the clarification, @kaamui. At least you listed the dependencies to be considered.  :-)

DJuego
