### ISSUE TITLE
Size of Lasor Pointer

### ISSUE THREAD

**Issue by Kryptos-123** [OpenBoard-org/OpenBoard#444]
Is there any way to adjust the size of the Lasor Pointer, maybe a config file that can be edited ? If so please guide .

**Comment by letsfindaway** [comment]
Currently the pointer diameter is a constant fixed in code with no option to change it. I think however that it is not too difficult to add this:

- as an option in the configuration, or
- as an additional selector next to the pen size and eraser size selectors in the top toolbar.

What option do you think is adequate? And to the OpenBoard team: what would you prefer? If it is in the settings, should it be on a separate tab? Probably also the color could be adjustable. I could look into this and provide a merge request for either way.

**Comment by Kryptos-123** [comment]
I think it would be more intuitive to have it as an additional selector next to the pen size and eraser size selectors in the top toolbar, also , the pointer could have a tab in the preferences to select the colors and sizes like the highlighter and pen have .

**Comment by kaamui** [comment]
hello,

Thank you for your feedback and thank you @letsfindaway for your really active support ^^

The most simple and not too much time consuming (also easier for me to review it) would be to make it a new setting added to the configuration file. No need to add a tab on the preferences just for that. A lot of other parameters are only editable using the configuration file.

**Comment by letsfindaway** [comment]
That seems to be the most simple solution and a first step. I think I can provide a merge request for that in the next days.

**Comment by maehne** [comment]
One thing, which I noticed related to this issue, is that the size of the Laser pointer is not set with respect to the screen size, but with respect to the imported PDF size. The size is OK for, e.g., PDFs of A4 documents and PowerPoint slides. However, the Laser pointer becomes unproportianally big if PDF slides are presented, which have been prepared with the LaTeX Beamer package. The latter PDFs have typically a size of 160 mm x 90 mm. It would be nice if this could be fixed as part of this issue.

**Comment by letsfindaway** [comment]
Thanks for reporting this. I will look into that. Might be a one-liner at https://github.com/OpenBoard-org/OpenBoard/blob/32ae89197adbc966196c23924d54ce27f58ffb9e/src/domain/UBGraphicsScene.cpp#L810. Others like the pen are additionally taking a `systemScaleFactor` into account -- the pointer doesn't.

**Comment by maehne** [comment]
Thanks @letsfindaway for looking into it and great if it is that easy to fix!
