### ISSUE TITLE
frames, zoom, shapes

### ISSUE THREAD

**Issue by driversat** [OpenBoard-org/OpenBoard#454]
hi, 
i am a teacher and i use openboard daily at work.
i noticed sometimes that clicking many times on the textbox frame makes the app to crash.
i would like to request some features:
1- how to draw customized rectangular or circular frames ( in size & color )
2- decimal graduated zoom ( 1.xx X)
3- shapes: custom (color) semi-transparent full shapes.
thanks for this great app.
cheers.

**Comment by kaamui** [comment]
Hi,

> i noticed sometimes that clicking many times on the textbox frame makes the app to crash.

I'll need a reproducible scenario in order to fix it^^

> i would like to request some features:
> 1- how to draw customized rectangular or circular frames ( in size & color )

you can select a color and a size before any drawing. you can also scale up/down any drawing using the grey rectangle appearing around any selected object.

> 2- decimal graduated zoom ( 1.xx X)

Due to our limited resources, we won't be able to prioritize on this one. 

> 3- shapes: custom (color) semi-transparent full shapes.

you can create them on your favorite graphics editor and export them as svg or png, and add it to your images library on OpenBoard.

Please make sure to create one ticket by request/report.
