### ISSUE TITLE
Reorganized shape library

### ISSUE THREAD

**Issue by Gvf63** [OpenBoard-org/OpenBoard#456]
Almost a year ago I uploaded a reorganized and expanded version of the shape library #334. It does not require code checks. Is there a reason not to integrate it into the project?

**Comment by kaamui** [comment]
I'm not able to decide by my own of what has to be integrated on the application. As you follow and help the project for a while, you must have notice that we have very limited resources in order to handle every aspect of it. 

The main focus, that was recently on migrating to latest qt releases, is actually on bug fixing, and migration from qtwebkit and webengine. After that, I hope we'll be able to focus on the content of the right palette, that could be greatly improved, as you noticed.
