### ISSUE TITLE
OpenBoard suddenly not opening for last one week (Windows 8)

### ISSUE THREAD

**Issue by vicharswatantra** [OpenBoard-org/OpenBoard#459]
Hi Experts,

I have been using OpenBoard comfortably for last one year, But since last week-
1. OpenBoard is not opening.
2. There are NO error messages.
3. In the task manager it keeps displaying as running.
4. CPU usage goes up to 35% for Openboard
5. Problems persists even after- Restarting, Reinstalling and other usual steps. 
6. Ver-1.5.4
7. Computer Config (Same for last one year)- Windows 8.1 Pro, 2.49 Ghz, 8 GB RAM.

Kindly help.

**Comment by letsfindaway** [comment]
"It worked until yesterday!". Things like that can hardly be solved from remote without further information. I'm running Linux and don't have a Windows installation running here, but I try to ask some questions to track down the cause of the failure.

1. The first question is obvious: Can you remember anything you changed on this computer at that time? Think also of things you would consider unrelated! Have you installed or uninstalled another program? Did you update another program?
2. The second question aims to get more information: Try starting OpenBoard from a command window and add the `-v` option:
```
"C:\Program Files (x86)\OpenBoard\OpenBoard.exe" -v
```
Do you see any messages in the command window? There should also be a log file in a `log` directory below the user data directory. That's where also your `OpenBoardUser.config` file is located. Find and check the log file!

PS: I hope the path to the executable is correct. As I don't have Windows, I just guessed it from the information I have.

PPS and unrelated to your question: You know that Windows 8.1 is unsupported since quite some time if you don't by the extended support? Did you think about switching to another version or - even better - another operating system?

**Comment by kaamui** [comment]
Hi,

Due to our limited resources, we are not able to test support for Windows 7 or 8. Did you try to install [the latest version ](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/OpenBoard_Installer_1.6.1.exe) ?
