### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stepan-neretin7** [OpenBoard-org/OpenBoard#481]
Good evening. Please tell me how you can remove the frame in the editor, so gray so thick?

**Comment by letsfindaway** [comment]
Have you already found the difference between the pointer tool (arrow icon) and the "magic finger" tool? The gray frame only appears when you select a widget with the pointer tool. The frame contains the menu buttons and allows e.g. to resize the widget. If you need access to such things, you should use the pointer tool - and this gives you the gray frame.

With the magic finger the gray frame is not shown, but you can still interact with the widget itself. You can e.g. operate the stopwatch application by clicking on its elements. But the gray frame does not appear, and therefore you can e.g. not delete the widget with that tool.

**Comment by stepan-neretin7** [comment]
I would like to remove this gray [frame](https://imgur.com/a/ULlLL9G), since it is possible to write outside the border of this frame, but at the same time why does it limit something then. It's stupid and annoying

**Comment by stepan-neretin7** [comment]
@letsfindaway

**Comment by letsfindaway** [comment]
Hi stepan,

why do you mention me? Do you expect me to solve your problem?

Let me first start with some words about what I find annoying. Its people using open source software, and still have only their own wishes and needs in mind and questioning the intents of the software authors, which put a lot of effort into this piece of software. So next time, rephrase your question. Because when saying this rectangle would be stupid and annoying, you suggest somehow that the programmers were stupid and their intent is to annoy you. This is not the case.

The rectangle is some kind of ruler for the user to see, what the recommended drawing area would be. It can be adjusted to a 4:3 or 16:9 ratio and is especially useful in multi monitor mode to have some idea on what fits on the second monitor.

You might have another use case. And it might be, that you would rather not have this rectangle. So what?

See, its open source! If you think it would be useful for others to make this rectangle adjustable, just do it! Fork the repository, add some code to make this configurable, offer it as pull request.

To give you a hint for starting: the rectangle is drawn starting at https://github.com/OpenBoard-org/OpenBoard/blob/f3f07f9930660a29eaa3cc95c86d6534109c8931/src/board/UBBoardView.cpp#L1695.

And I also suggest to read some texts about how to ask a question, e.g. https://github.com/selfteaching/How-To-Ask-Questions-The-Smart-Way/blob/master/How-To-Ask-Questions-The-Smart-Way.md. Just some points:

- Find a good title.
- Describe your problem exactly, so that others can understand it.
- Be polite. You want people to help you in their spare time.

Better luck with these three points next time.
