### ISSUE TITLE
Add these addons by default ?

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#484]
Hi, I work with teachers and I often have to manually install these cool addons : http://fanch.le.cleach.free.fr/index.php/open-sankore/applications-pour-sankore/

But for some teachers, installing an addon is not an easy thing... Would it be possible to enable them by default ?

**Comment by SeeDborg** [comment]
I'm proposing it because I saw you already added the addon "paper" in your latest release. Why not the others ?

**Comment by LeSnake04** [comment]
I don't know French, so I cant read the Website...

1. Does the plugins also have at least has English version
2. Is it open source (if yes,please link the repo)

**Comment by LeSnake04** [comment]
Just tested some of the plugins: every plugin is only available in French (tested it with openboard set to English and German)

**Comment by kaamui** [comment]
Hi,

Papier has been added because the team asked for it, and because it was already available for our Mac users. I think there is some code for translations in it, but not sure why it's not working. 

In general, we try to limit the default amount of content, so Openboard stays as light as possible. The idea is that everyone can create its own library (you can add every widget you mentioned yourself by placing them on the applications folder).

**Comment by SeeDborg** [comment]
Thank you, but for some teachers, installing additionals plugins can be really hard, That's why I asked for this.

**Comment by kaamui** [comment]
I understand. One solution that I hope to see happen one day, is to have an online platform where you can download resources like HTML widgets. Something similar to Planete-Sankore.org , that was available some years ago.

**Comment by SeeDborg** [comment]
It would be very nice indeed.
I'm learning french teachers how to use OpenBoard, they love it but they usually struggle to add plugins ^^
