### ISSUE TITLE
Wacom cursor is invisible - OpenBoard v1.6.1 - Fedora 33 - Flatpak

### ISSUE THREAD

**Issue by bbigby64** [OpenBoard-org/OpenBoard#487]
I installed OpenBoard v1.6.1 on my Fedora 33 system via Flatpak.  I have a Logitech mouse and a Wacom Bamboo Tablet with an accompanying pen.  With the mouse, there is a visible cross cursor and although when I begin drawing, it disappears, it returns when I stop drawing -- fine.  However, with the Wacom Bamboo tablet, a cursor never appears.  It's kind of hard to use the Wacom tablet when I never know the location of the tablet cursor.

**Comment by bbigby64** [comment]
Update: I just installed Fedora 34 in GNOME Boxe, installed OpenBoard v1.6.1 into the VM, and the problem does not appear to exist.  I guess that the problem is specific to Fedora 33.  I event rebooted my Fedora 33 host box and the problem persists.  Therefore, I'm not sure that this is a problem with OpenBoard.

**Comment by bbigby64** [comment]
The same thing is appears in Fedora 34.

**Comment by RickGxG** [comment]
Maybe this answer can help for those using OpenBoard and Wacom tablet in Ubuntu 22.04. Posted first: https://github.com/OpenBoard-org/OpenBoard/issues/514

I had a similar problem in Ubuntu 22.04 with OpenBoard 1.6.4 and a basic Wacom One tablet. It seems to be a problem with Qt and Wayland. I think the problem arises because OpenBoard is always in fullscreen. I have three workarounds:

1. Activate "Locate Pointer" in Ubuntu Settings > Accessibility. When the Ctrl key is pressed, the tablet pointer becomes visible for a moment. 
2. Select the "MultiScreen" option from the OpenBoard Menu (the little gear icon located below the close button). This action breaks the fullscreen mode and enables the tablet pointer visualization. Note: Some actions, like opening saved slides, might set OpenBoard back to fullscreen mode. 
3. Uninstall the old version and install OpenBoard 1.7.3 (in my case for Ubuntu 22.04, from [here](https://github.com/OpenBoard-org/OpenBoard/wiki/Downloads#other-platforms)). This version has the RunInWindow parameter, which must be set to true in OpenBoardUser.config file, normally located in the .local/share/OpenBoard/ folder. See OpenBoard [Configuration](https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration) and [Parameters](https://github.com/OpenBoard-org/OpenBoard/wiki/Parameters). 

I think the last procedure is the best, even though it doesn't fix the root cause.
