### ISSUE TITLE
Openboard Documents empty after being in trash en dragged back

### ISSUE THREAD

**Issue by esd31415** [OpenBoard-org/OpenBoard#490]
This morning I tried to delete an empty document that automatically opened when I started up Openboard, but then all my documents were placed in the trash. I didn't see a button to return them to documents so I dragged them back to the documents area. But then I found out that most of my documents missed a lot of pages, mostly the same pages that I also added to new documents, and some documents were duplicated up to 9 times (and most of them were empty, some had 1 random page). Also, in some documents there are pages that were orginally in other documents, for example a page about shapes was in a document about powers and roots. 

I lost all my documents that were my lessons for this school year, so I really hope somebody knows how to fix this. I haven't tried restarting my computer, I did try to restart Openboard but it was all still the same. I haven't exported the files onto my computer so right now I basically lost everything.

**Comment by kaamui** [comment]
Hi,

On what operating system are you ? What version of OpenBoard ?

From what you explained, there is no reason your documents can be definitely deleted. Moving them to OpenBoard's trash doesn't erase them on disk, but simply mark them as "inTrash". You have to empty the trash for them to be completely deleted on disk. Also, there is no known issue where dragging back documents would completely mess up their pages. With 1.5.4 though, it was possible that some documents would enter in a bad state regarding the number of pages referenced in the metadata file. If manipulating while in this bad state, some pages could be lost. 

> But then I found out that most of my documents missed a lot of pages,

From my current knowledge of the issues one can encounter in OpenBoard since 1.5.4, this cannot happen by moving documents from "MyDocuments" to "Trash". What could happen is that some action (like deleting a page in Board Mode and exit OpenBoard right after, etc.) could  result in the "ub:page-count" having an incorrect value. If it happened to most of your documents (not all, and not one or two), it might be caused by the way you make them (not to say it's your fault, but that you may have encountered the same bug over and over, and didn't notice it before this morning)

> mostly the same pages that I also added to new documents

Can you clarify how you added these pages to new documents ? 

>  and some documents were duplicated up to 9 times (and most of them were empty, some had 1 random page).

We never had this kind of bug reported, but it looks like multiple "corrupted page-count" issues we are aware of with 1.5.4 (but it would corrupt an active document, one at a time, not most of them in one action). 

> Also, in some documents there are pages that were originally in other documents, for example a page about shapes was in a document about powers and roots.

I'm not sure how this could happen without any manipulation regarding pages between documents (in Document Mode, moving a page from a document to another). Is it possible you may have mistaken the destination of your duplicated pages ?

It seems to me quite impossible for any part of the code to achieve such things just by using drag'n'drop between "My Documents" and "Trash"

We are aware that when in Documents Mode, it is not always simple to tell where the focus is, so be sure to always click on the document(s)/page(s)/folder(s) you want to remove before clicking on the trash, until we improve the UI of this mode so it is clearer from the user's point of view what is focused. 

Please download [the latest version](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.1) of OpenBoard that has been recently released.

Also, Please be advised that you can make regular backups with OpenBoard using the "export to UBX" action on the root folder. 

I'm afraid I can't do anything in order to help you recover your files, but at least we can try to check them, one by one, to save what can be saved. 

If you are on Windows, you can find your documents on %localappdata%/OpenBoard/document (open Windows file explorer and copy/paste this path). 

Each "OpenBoard Document 20yy-mm-dd hh-mm-ss.ms" you find here is one of your documents.

For documents you suspect to have a wrong value of the number of pages in the metadata file, enter into and verify that the number of pageXXX.svg and the "ub:page-count" in metadata.rdf match. If not, fix the metadata value with the correct value.

Once every document is fixed, launch OpenBoard (not before, as it could end in overwriting some pages, if values of page-count metadata were still corrupted)

Please tell me how many of them you find in a bad state. 

Hope it helps.

**Comment by esd31415** [comment]
Thank you for your response. I'm on Windows 10 and I'm using Openboard 1.5.4.
My documents indeed aren't completely deleted, they are all still there, but incorrect. They contain less pages, different pages from another document or they are empty. 
I checked the folder via local app data and in there I can see the previews of pages as they are now, so those are the incorrect documents. I can see that the pages that weren't in a document originally, are placed in there on the time I dragged all the documents back to 'My documents' from 'Trash'. I selected them all and then dragged them there. The pages that are still correct have a different date of last modified, most likely the date that I last edited the document. If I enter the metadata of a document, the number of pages that it counts with ub:page-count doesn't match the number of pages the document actuallly has. For example: one document has one page when I open it, but in the metadata it says 7 pages. That document also has 3 empty duplicates (that I did not make myself). However, I don't know where I can find pageXXX.svg, so I can't compare the number to that. I added two images of the metadata and the corresponding document that I see in Openboard. 
![document](https://user-images.githubusercontent.com/84778780/119708584-96ba6a00-be5c-11eb-908f-cf7d66ee4f59.jpg)
![metadata](https://user-images.githubusercontent.com/84778780/119708586-97530080-be5c-11eb-8dcf-76ab2ea74e5a.jpg)

I use the same structure for every document and I therefore usually duplicate an already existing document and change some things in the duplicate to make a new complete document (lesson). I use the same starting page and a page where I tell the students which excercises they have to make, and those two seem to be gone in almost every document. It was just a regularity that I noted. Also, most images are not visible anymore, I can see them when I'm in document mode but when I open a page, the image is not there.

I did find another abnormality (that I am however quite happy about). There are some documents that are still complete. All those documents have a specific last modified date. There are three different dates and about a third of all my documents is complete and so called last modified on one of these three dates. Two of the three dates (10/09/2020 and 10/11/2020) are impossible for me, since I didn't even have my laptop then, and I am therefore sure I did not make or edited those documents on that day. The other date is 01/02/2021. All the documents that are last modified on one of these three dates are still correct and complete (including images). I have no idea how this is possible and why this is, it all seems so strange what happened and this only adds to that.

Thanks again for you help. I sort of gave up on restoring everything already, since most documents are a mess and it's just so random and weird how this happened.

**Comment by kaamui** [comment]
By PageXXX.svg I meant that every page of your document are named like this inside every OpenBoard document folder (at same level as metadata.rdf). For example, if you have one openboard document with 3 pages, you'll find them in the document folder as page000.svg, page001.svg and page002.svg, with the metadata ub:page-count equal to 3. If not, you could loose data, so it is important to restore this metadata value.

If one day you find the way to reproduce the bug systematically, please give me the scenario here so I can fix it. 

Thank you, and sorry for the inconvenience !

**Comment by esd31415** [comment]
I haven't been able to reproduce it, I will let you know if I do.

I downloaded version 1.6.1 and the tool for making a snapshot of a part of the screen isn't working properly. When I click on it, my whole screen turns black. I use two screens and that problem only appears when I'm working on the second screen.  I used that tool a lot, it always saved me a lot of work, so I hope there is a way to fix that. Thanks again!
