### ISSUE TITLE
PDF export does not work in Rel 1.6.1

### ISSUE THREAD

**Issue by gadsy** [OpenBoard-org/OpenBoard#521]
Yesterday 9/26/21 I updated OpenBoard to Release 1.6.1 and PDF export stopped working. It shows every step but no PDF was found and there was not any error message. I tried with different names and locations but no PDF was built. I uninstalled it and reinstalled release 1.5.4 and the export feature began working again.

**Comment by kaamui** [comment]
Hi,

what OS ?

**Comment by chcolo** [comment]
Hi, Exactly same for me. I check that when i export a doc to pdf the pdf don't appear and the computer made a sound at the end of exporting process. Strangely if you export to an usb pen it works. 
I try to save an exported pdf doc from open office and it works perfectly so the problem is from openboard...
