### ISSUE TITLE
Dots issue v 1.6.1

### ISSUE THREAD

**Issue by bronskeey** [OpenBoard-org/OpenBoard#537]
After updating version to 1.6.1 I start to having those dots at the beginning of every line. I can switch versions back and forth to repeat this problem, so I think it's version related issue.

Driver reinstalled, OpenBoard reinstalled, tablet replugged.

Windows 10 Pro 20H2
Wacom Bamboo CTL-470K
OpenBoard 1.5.4, 1.6.1

![v 1 5 4](https://user-images.githubusercontent.com/88116571/139594668-c7266739-b12a-4671-b1ca-3aa5349677cc.png)
![v 1 6 1](https://user-images.githubusercontent.com/88116571/139594670-5a6e9d9e-18b5-409e-a420-e4a5f07ef789.png)

**Comment by GabiKleebi02** [comment]
I have the same issue. For clearance, I made a video of me writing something and how the dots appear when drawing a new line.

https://user-images.githubusercontent.com/31568602/139919180-6bd5cba3-28aa-4ce1-851c-f1488b94c521.mp4

**Comment by ansobolev** [comment]
Same here. I guess this has something to do with the fact that Windows recognizes every single touch of the tablet as a left mouse button click. Openboard 1.5.4 somehow filtered those events, but Openboard 1.6.1 does not.

**Comment by letsfindaway** [comment]
OpenBoard did not change the way these events are processed between 1.5.4 and 1.6.1. But of course the underlying Qt version was changed. So it might also have to do with that. The video of @GabiKleebi02 shows that it does not happen on each stroke. So I assume it is even timing related: What is delivered first: the pen or the mouse event?

Generally speaking: IMHO a tablet driver should not send mouse events at all. For Qt it is the opposite way: If a program or a widget does not process a tablet event, then - and only then! - Qt also sends a mouse event, so that programs not aware of tablets can also work with them. But a driver should not do that. So I would call this behavior a driver bug.

Is there any option to switch this behavior on and off in your driver? If not, I could just think of a filter in OpenBoard as follows:

- Recognize the `TabletEnterProximity` and `TabletLeaveProximity` events.
- Suppress mouse events reaching the `UBBoardView` between those two events.

**Comment by ansobolev** [comment]
The dots appear for smaller strokes. If the stroke is somewhat long, then everything is fine. I investigated issue a little bit and found, that if I untick the "Use Windows Ink" option in the Wacom tablet properties, the issue goes away. However, so does pressure sensitivity. I can live without pressure sensitivity, so as of now I resorted to this option.

**Comment by letsfindaway** [comment]
See https://bugreports.qt.io/browse/QTBUG-93889. Is this probably related? Could you try the command line option `-platform windows:nowmpointer` mentioned there?

Strange that it depends on the stoke size. The dot is in the beginning. And when you start drawing the size of the stroke is obviously unknown - else I would loose my belief in causality ;)

**Comment by ansobolev** [comment]
Yes, I can confirm that with the aforementioned option the dots are gone! Thank you! I think I can just add that option to a desktop shortcut.

By the way, causality is ok; the dots appeared _after_ the stroke is done, but _in the beginning_ of the stroke, and not where the pointer is.

**Comment by thegyl** [comment]
Sorry if I am re-opening the topic, but I have the same issue, and I can't fint the way to solve it.
Where shoult the command -platform windows:nowmpointer be used?

**Comment by letsfindaway** [comment]
I don't know exactly how it looks on Windows, but I assume if you have a shortcut on your Desktop you can right-click on it, edit it and add `-platform windows:nowmpointer` as parameter here?

**Comment by GabiKleebi02** [comment]
I'll try to describe it detailed:

If you have a shortcut on your desktop (or somewhere else):
1. Right-click the shortcut
2. Open 'properties' --> you should than be in the shortcut tab of the new window
3. in the target field you append `-platform windows:nowmpointer`

If you open OpenBoard by searching for it in the Windows start menu:
1. Search for 'OpenBoard'
2. Expand the menu (if not expanded already) by clicking the arrow icon below 'Open'
3. Click 'open file path'
4. In the target field you append `-platform windows:nowmpointer`

**Comment by thegyl** [comment]
Thank you! You made it very clear, and it works :)

**Comment by aditya2305** [comment]
I appended "-platform windows:nowmpointer" after target but still not able to rectify the problem. Any suggestions?

**Comment by Rohanfizz** [comment]
> I appended "-platform windows:nowmpointer" after target but still not able to rectify the problem. Any suggestions?

Same here :'(

**Comment by aditya2305** [comment]
I found a workaround, In open board go to settings and turn off press sensitivity

**Comment by GavinSmith0123** [comment]
I confirm that `-platform windows:nowmpointer` is needed. This is for Qt 5.15.2 on a Wacom tablet with Windows Ink enabled. As someone else said, the dots only appear for small strokes. After reading of many similar problems online I suspect it is something to do with the "pen flicks" feature, which is presently impossible to turn off in Windows 10.

Turning off pressure sensitivity is not an option either as this is needed to get the first part of a stroke - it would either be missing or appear as a straight line, badly mangling handwriting. Again there are many reports of this problem for different programs under Windows 10, with no fix as Windows has removed the options to disable pen flicks or Windows Ink. The only option seems to be for the program to interpret pen events rather than mouse events, which pressure sensitivity does in OpenBoard.

I'm also trying to use OpenBoard on a CleverTouch whiteboard, although haven't been able to test this work-around yet. I expect that pressure sensitivity has to be on as well as adding this option to the command line.

**Comment by aceradryd** [comment]
> Turning off pressure sensitivity is not an option either as this is needed to get the first part of a stroke - it would either be missing or appear as a straight line, badly mangling handwriting. Again there are many reports of this problem for different programs under Windows 10, with no fix as Windows has removed the options to disable pen flicks or Windows Ink. The only option seems to be for the program to interpret pen events rather than mouse events, which pressure sensitivity does in OpenBoard.

If it is possible for you to compile OpenBoard yourself, you can try to replace the following lines of code with my code.
This way the tablet function is used until the end and straight lines at the beginning of a stroke disappeared for me.

https://github.com/OpenBoard-org/OpenBoard/blob/d4b91d8d34744ff33ca4d16e02dd60041cd82c52/src/board/UBBoardView.cpp#L369-L377

```
    qreal pressure;
    if (((currentTool == UBStylusTool::Pen || currentTool == UBStylusTool::Line) && mPenPressureSensitive) ||
            (currentTool == UBStylusTool::Marker && mMarkerPressureSensitive))
		pressure = event->pressure ();
	else{
        //Explanation: rerouting to mouse event
        //event->setAccepted (false);
        //return;
		pressure = 1.0;
    }
```

**Comment by GavinSmith0123** [comment]
> > Turning off pressure sensitivity is not an option either as this is needed to get the first part of a stroke - it would either be missing or appear as a straight line, badly mangling handwriting. Again there are many reports of this problem for different programs under Windows 10, with no fix as Windows has removed the options to disable pen flicks or Windows Ink. The only option seems to be for the program to interpret pen events rather than mouse events, which pressure sensitivity does in OpenBoard.
> 
> If it is possible for you to compile OpenBoard yourself, you can try to replace the following lines of code with my code. This way the tablet function is used until the end and straight lines at the beginning of a stroke disappeared for me.
> 
> https://github.com/OpenBoard-org/OpenBoard/blob/d4b91d8d34744ff33ca4d16e02dd60041cd82c52/src/board/UBBoardView.cpp#L369-L377

Thanks. I did something very similar (https://github.com/GavinSmith0123/OpenBoard/commit/36c6a4cb78646c42bbcb8f32788e41f105548196).

According to Qt documentation, tablet events should be used if they are available: https://doc.qt.io/qt-5/qtabletevent.html:

> Qt will first send a tablet event, then if it is not accepted by any widget, it will send a mouse event. This allows users of applications that are not designed for tablets to use a tablet like a mouse. However high-resolution drawing applications should handle the tablet events, because they can occur at a higher frequency, which is a benefit for smooth and accurate drawing. If the tablet events are rejected, the synthetic mouse events may be compressed for efficiency.

I found that `-platform windows:nowmpointer` had to be removed from the flags to get this to work on a Clevertouch Impact whiteboard, though. (Clevertouch boards aren't pressure sensitive.) The dots issue is gone although I don't really know why.

**Comment by AmitMourya1322** [comment]
Use this method all above method are useless and i try my method is 100% working with prove
[My Method](https://youtu.be/jmZ2FQAy9d8)

**Comment by Roberto888888** [comment]
> Use this method all above method are useless and i try my method is 100% working with prove .Please Watch the video to understand how to resolve it [My Method](https://youtu.be/jmZ2FQAy9d8)

I can confirm that this works and not only that, it even makes handwriting much much smoother (at least in my machine).

Briefly, the solution is to change the compatibility of OpenBoard to Vista and I don't know if that has any side effects, so far I didn't notice any.
