### ISSUE TITLE
Next version ?

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#562]
Hi,
I see there are lots of unresolved issues for the OpenBoard project.
I love to use it with my students, so I would like to know if it's still in development and if there is a new version coming soon.
Regards.

**Comment by letsfindaway** [comment]
OpenBoard is under active development, but it is moving slowly. I'm not the project maintainer and I can't tell about detailed plans and timeline. But there is at least the following in the pipeline:

- There will be a 1.6.2 bug fix release, and I hope this will come quite soon. You see the current work on that in the `dev` branch here: https://github.com/OpenBoard-org/OpenBoard/tree/dev
- There will be a 1.7.x feature release later, which replaces QWebKit by QWebEngine as the browser engine used by OpenBoard. You see the current work on that in the `1.7-dev` branch here: https://github.com/OpenBoard-org/OpenBoard/tree/1.7-dev

**Comment by kaamui** [comment]
1.6.2 should be available before June.

1.7 is not perfectly scoped at this time (mainly because of the needed support of ARM processors on osx, which will probably need openboard to be migrated to Qt 6.2...). Depending on the decision that 1.7 release should provide native support for ARM-based machines, it could delay it a lot.

Now that 1.6.2 is about to be released, discussions will start about 1.7. I'll let you know what has been decided as soon as I can, but don't wait 1.7 to be released this year.

**Comment by SeeDborg** [comment]
Anyway guys, thank you so much for the answers.
I am really happy to hear that OpenBoard is still in active development, and I look forward for the next versions !

**Comment by kaamui** [comment]
It is ! But we are really a small team so everything takes a while ^^

**Comment by ivanavucka** [comment]
May I know if there is any progress made and planned with the embedded browser? Can this technology (the web widgets) be implemented to integrate with my website, maybe as a standalone? I want to have a browser that is shared so two (or more) people can browse together and ideally also annotate, and to have an audio and video call and a chat added. Can this embedded browser integrate like that Thanks in advance for pointing me in the right direction.

**Comment by letsfindaway** [comment]
Since version 1.7.0, the integrated browser provides a Chrome-based browser engine, which can render all modern web sites. Just check it out!

You can copy/paste the URL of your web site to the board to create a web widget containing that web site.

OpenBoard however does not have a built-in video conferencing tool. And it also does not allow annotating by multiple people. But what you can do - I just tried it:

- Start OpenBoard
- Go to Web mode - the integrated web browser
- Use any web based video conferencing tool like Jitsi to create a web conference. Invite the others.
- Share your screen in the video conferencing tool
- Then switch to Board mode. The others now see your board, even if you no longer see the others.
- Copy/paste the URL of your web page to the board to create a web widget with your web page. Position and resize it as needed.
- Now you can interact with the page and make annotations and the others see what you do.

But as I said: OpenBoard cannot provide collaborative editing this way.

BTW: Instead of using the built-in web browser for the video conference you can as well use another browser. If you have two screens, then you could even move the browser to one screen and work with OpenBoard on the other.

Just make your own experiments!
