### ISSUE TITLE
Missing MSVCR100D.dll

### ISSUE THREAD

**Issue by DoctorWkt** [OpenBoard-org/OpenBoard#57]
An earlier version of OpenBoard was running on my work laptop which has Win 7 on it. Now, the latest version tells me that MSVCR100D.dll, and I should reinstall the program.

Any ideas on how to fix this new problem? Thanks, Warren

**Comment by ramuntcho** [comment]
Hi,

It probably lacks some resources in our last release. It will be fixed as soon as possible

**Comment by c2701** [comment]
I got this problem too with current version (1.3.3). Tried all known solutions for repair MSVCR100D.dll error, but no success. Finally, I installed previous version (1.3.1) and my touch screen works fine.
Looking forward for a fix

**Comment by freeheel3r** [comment]
Hi,
First of all, my apologies for the slow replies lately. Future (and current) issues should be addressed more timely in the coming days.

And thank you for bringing this to our attention. I believe I've tracked down the problem and I have created a new installer for version 1.3.3. Could you please tell me if this fixes the issue?

(I have tested it on a clean install of Windows 7, and it works on my end)

Here is a temporary link -- if it does indeed work I will post it on the release page here. https://dl.dropboxusercontent.com/u/1062506/openboard/OpenBoard_Installer_1.3.3.exe

**Comment by c2701** [comment]
Hi Craig
Nice job with your program... keep going.
 
I run the installer in VBox and got an error (see attachments) even I have required library. Anyway - it seems to work fine.
After some tests, 'Tools' button in Web tab - not working and Some websites not loading correctly. Otherwise - I see no problems.
C2701
Hi,
First of all, my apologies for the slow replies lately. Future (and current) issues should be addressed more timely in the coming days.And thank you for bringing this to our attention. I believe I've tracked down the problem and I have created a new installer for version 1.3.3. Could you please tell me if this fixes the issue?(I have tested it on a clean install of Windows 7, and it works on my end)Here is a temporary link -- if it does indeed work I will post it on the release page here. https://dl.dropboxusercontent.com/u/1062506/openboard/OpenBoard_Installer_1.3.3.exe—

**Comment by freeheel3r** [comment]
Hi,

What error did you get? I don't see any attachments (I think you have to comment directly on GitHub rather than by email to attach files).

About the web browser: there are indeed a few issues (known or not), but it's not clear if and when we will correct them, as it isn't an essential feature.

**Comment by DoctorWkt** [comment]
Thanks c2701, yes the new install binary works fine and I can run OpenBoard again!

Cheers, Warren

**Comment by c2701** [comment]
Hi Craig
I cannot add print screen (got an error 'unsupported file')
Anyway - my error when installing OpenBoard - was saying 'Microsoft visual C++ 2010 x86 redistributable setup has detected that this computer not meet the requirements....'
and asking me to resolve the following:
'A newer version of MS Visual C++ 2010 has been detected on the machine'
As I said before - even with this error - ver. 1.3.3. seems to work fine...

**Comment by freeheel3r** [comment]
Ah, I see. That's quite OK actually, part of the issue was that the wrong version of Visual C++ redistributable was included in the OpenBoard installer, so I switched it for a working version. Since many applications also include this, it's usually already on one's computer when OpenBoard is installed.
I'll see if this "error" can be silently ignored, or if I can package a different version of Visual C++ to avoid this altogether.

Thanks again for your help!
