### ISSUE TITLE
Possibility for snapping to top/bottom/left/right side of the screen

### ISSUE THREAD

**Issue by IzaacJ** [OpenBoard-org/OpenBoard#626]
Hello.

I love using OpenBoard for notes during meetings, but it would be a bit better and smoother if it were possible to snap it to either left or right side of the screen when in landscape mode, or top or bottom of the screen when in portrait mode.
I understand if it is outside the scope of the project, but it feels like it would be a great addition.

Note: Using a Samsung Galaxy Book Pro 360 with touchscreen and an S-pen.

**Comment by letsfindaway** [comment]
I think snapping a window to the edges of the screen is **always** an action of the respective window manager and never a task the application can and should do. So check what your window manager can do or look for tools which provide such a behavior. But I think you could close the issue here. As you already mentioned, it is outside the scope of this project.

**Comment by IzaacJ** [comment]
> 

It doesn't work with Openboard since it's always fullscreen when in Board mode. In desktop mode it hides the board and only shows the popout drawers.

I use Win+arrows shortcut for this normally, and since there's no window bar at the top it is impossible to drag it into the snapping zones as well.
