### ISSUE TITLE
Unusable cross dark background

### ISSUE THREAD

**Issue by evantill** [OpenBoard-org/OpenBoard#63]
Hi,

When using the dark background with the grid, we can not see the grid.

The color used for the grid is `rgb(44,44,44,200)` (see [UBSettings.cpp](https://github.com/OpenBoard-org/OpenBoard/blob/0b2f8bfb56741e021326271ee3e18284b338c2e5/src/core/UBSettings.cpp#L74) )
which is too dark.

Please consider using a brighter color like `rgb(209, 209, 209)`.
Or maybe add this color to the preference panel to let user change it.

**Comment by freeheel3r** [comment]
I can see it just fine :)

Actually on my screens a brighter colour would be disturbing. I imagine on a display with low contrast ratio and/or resolution, the grid wouldn't appear as clearly. 
So since it depends on one's configuration we can't change the value for a brighter one for everyone.
But it could be nice to have this as a user setting, so if and when I have the time I'll do that, and it will be possible to set this value in the OpenBoard.config file.

That said, if you'd like to do it yourself, please feel free to do so and submit a pull request. I'll definitely accept a new setting in the config file (adding it to the settings window may be overkill though, we normally try to keep it as basic as possible).

**Comment by evantill** [comment]
Here some screenshots on my mac book pro (mid 2009)

![plein_ecran_03_10_2016_14_30](https://cloud.githubusercontent.com/assets/609288/19037412/6727b808-8976-11e6-8b2b-6f2b5c9dacc3.png)

![plein_ecran_03_10_2016_14_30]
(https://cloud.githubusercontent.com/assets/609288/19037397/57a7a14a-8976-11e6-8412-0e5e45494241.png)

I will try to do it myself.

**Comment by freeheel3r** [comment]
Huh, that's odd. It should be a lot more visible than that.
Thanks, I'm sure this will be useful to other people too. If you'd like any help with implementing it just let me know!

**Comment by freeheel3r** [comment]
I ended up implementing this as a setting in the configuration file: see commit 2fd0cc8
