### ISSUE TITLE
Wacom Stylus Windows 10 delay

### ISSUE THREAD

**Issue by audimax85** [OpenBoard-org/OpenBoard#64]
I have a Lenovo Helix 1st gen tabelt with integrated wacom stylus (Feelt IT driver).

If i write on the whiteboard there is a serious delay in recognition.

If i try to draw a circle there is first a dot and afterwards a straight line.  Oviously the input recognition suffers from a delay which makes writing text impossible. Text shows up only as a set of garbled lines.

Ist there any way i can help diagnose the cause of this problem? A log or a screenshot or anything?

By the way: in NoteOne there is no problem. Everything is recognized as it should be.

PS: Thank you for this otherwise great software! Keep up the good work!

**Comment by evantill** [comment]
Could you try to draw with your finger ? Is the problem the same ?

**Comment by audimax85** [comment]
With finger input it is much less obvious, but the problem seems to be the same.

**Comment by evantill** [comment]
In the preferences could you test to disable the option `Marker is pressure sensitive` ?

![preferences_et_openboard](https://cloud.githubusercontent.com/assets/609288/19143328/80a33468-8ba3-11e6-9367-5dedfd643527.png)

**Comment by moutarde77** [comment]
Bonjour,
j'ai le même problème depuis des années... La dernière version d'Open Sankoré qui permette une écriture fluide (sans "delay") est la 1.26.00. Dès les versions suivantes (y compris toutes les versions d'OpenBoard), l'écriture n'est plus fluide (voir post #23 ). Après des heures et des heures d'essais, j'ai remarqué que la dernière solution fonctionnelle pour moi (sur Microsoft Surface Pro 2) est la combinaison de la version 1.26 de Sankoré et la version 7.3.2.12 des drivers ISD Wacom (http://cdn.wacom.com/u/drivers/TabletPC/ISD_DualTouch_732-12.exe). Avec des versions plus récentes, impossible d'avoir une écriture lisse et réactive. Ce qui est étonnant, c'est que, comme dit plus haut, les logiciels tels que OneNote, Paint, Photoshop, ou autres, fonctionnent très bien avec les versions les plus récentes des drivers Wacom. Il doit donc y avoir un souci entre OpenBoard et les drivers Wacom actuels (7.3.4.8). Ce problème ne varie pas, que l'on coche l'option "stylet sensible à la pression" ou non.

**Comment by evantill** [comment]
I will reply in French to @moutarde77 but if someone needs it in English I will translate later on.

@moutarde77 merci pour votre retour d'expérience. Vous êtes aussi sous windows 10 ?

Je me demande si le problème n'est pas plus sur la librairie Qt et ces différentes versions. J'aimerais tester avec une application simplifiée avec uniquement la partie gestion du stylet.

**Comment by freeheel3r** [comment]
@audimax85 thank you for your report. Unfortunately I really don't know how I can solve this problem or even diagnose it well since I don't have that hardware and I've never had that issue with any tablet I've used so far. The writing isn't great (more on that later) but I've never seen it be as bad as what you described.
Off the top of my head, the only possible fixes I can think of would be to either change drivers, or check if you can adjust the polling rate of the tablet.

Anyway, regarding the writing in OpenBoard: (answering in English as this is likely to come up often)

In its current form, OpenBoard will simply not get faster tablet input. It is a limitation of the libraries on which it is built and it runs very deep; there's no way to change that without a huge overhaul of the codebase. The reason for this, briefly, is that the libraries handling the GUI are not hardware-accelerated (they don't use OpenGL). Most drawing programs -- and actually, any program written with modern Qt libraries like Qt Quick -- use an OpenGL backend, making them inherently faster.
If anyone has more specific questions I'll gladly answer them but this pretty much sums it up.

Now, that is only one aspect of a "smooth" writing experience. The other, arguably more important point is modifying the strokes being drawn to make them look smoother. We've already discussed this in issue #23 but long story short, I'm working on that and there's already a decent improvement. This, along with a few other new features, will be part of version 1.4. Experimental versions will be available soon, hopefully in the coming week(s), but most of this code is on the `1.4-dev` branch.

**Comment by moutarde77** [comment]
@evantill Oui, je suis sous Windows 10, mais j'ai constaté ce même problème sous Windows 7, Windows 8/8.1 déjà, avec mes différents TabletPC cités plus haut...

@freeheel3r Thank you for your explanations and your great work. Looking forward to v1.4!

**Comment by audimax85** [comment]
@freeheel3r 
Thank you for your answer and your efforts. I apologize for not returning for such a log time.
After playing around with different Versions of Open Sankore, Open Board and the "Feelit" Driver from Wacom i found (thanks @moutarde77 ) that with driver Version 7.3.4-8 (latest) in OpenBoard (and Easitech and Xournal) there is the described issue. in Open Sankore the writing is totally smooth, but there is a pretty serious displacement issue (line is off by half the screen).
With driver 7.1.2-9 the writing is smooth in OpenBoard, Open Sankore and Xournal  but there is no palm rejection. Easiteach has the original issue.
7.3.2-12 does not work at all in windows 10.

The polling rate does not seem to be adjustable.
My guess by now is, that windows 10 added new options in accessing a stylus device with certain modes that give additional data in the beginning...

**Comment by ootwch** [comment]
Not to this one: The issue with the dot at the beginning of the line is due to Qt sending a mouse event even if the tablet event is handled - although the documentation says otherwise. My PR fixes this.

**Comment by AkashCherukuri** [comment]
Writing this here in case someone stumbles upon this trying to fix their problem.
---
I'm using **Wacom One** with **Windows10**, and there was a lag in the input being registered.

Reinstalling Wacom One drivers from [here](https://www.wacom.com/services/wacom/get-download-url.aspx?plat=win&dver=6.3.13w3&dt=drivers&redirect=true), and following their instructions solved the problem for me.
