### ISSUE TITLE
Crop image from Desktop showing just black picture

### ISSUE THREAD

**Issue by omkardongre** [OpenBoard-org/OpenBoard#665]
I am running openboard on Ubuntu 20.04. After opening openboard  and selecting Show Desktop option, I am unable to crop image.
Whenever I am cropping any picture from  Desktop or selecting screen shot option , it just display a black image on openboard instead of actual crop content from Desktop.

**Comment by letsfindaway** [comment]
I just checked this and it works for me with OpenBoard 1.6.3 on openSUSE Leap 15.4 with X11 as you can see:
![grafik](https://user-images.githubusercontent.com/35591413/193271444-682a166d-676a-4f0b-92bc-241065330e96.png)
Please tell more about your system, so that we can track down what makes the difference.

Some more explanations and questions:

- At the moment when you press the "Crop" button 
![grafik](https://user-images.githubusercontent.com/35591413/193271829-4ffe2a96-2e6b-44ab-8dde-91da8787e4fb.png)
OpenBoard creates a screenshot of the desktop and displays this screenshot instead of the actual desktop. You should not notice a big difference here, but just a question: Do you see a short "flicker" of the screen when you press this button? On my system I can detect that the screenshot is now placed on top of the screen.
- You can then select the crop area using the mouse. Interactions with the desktop are not possible in this phase. Does this still look reasonable?
- After that you get a menu asking you to add the image to the actual page or a new page. Do you also get this?

Not sure whether this is related, but a user reported this #579 and closed it the next day.

**Comment by omkardongre** [comment]
System information : 
RAM:16 GB
Processor Intel i7-10610U
OS: Ubuntu 20.04.5 LTS
OS type : 64 bit
GNOME version: 3.36.8
Windowing System : Wayland 

Answers to your following questions:

When I click on crop button, the whole desktop turns black, and when I crop any area , it display black portion cropped on openboard.

Yes after selecting crop area, it ask me menu asking to add image to actual page or new page.

Yes exactly similar black area appears if I take screenshot or crop any area from desktop. I think it the same issue mentioned in #579


Earlier I were trying openboard on  Windowing System : X11 on ubuntu
But on that none of the options of openboard was working their so from some sources I got to know it works fine on Wayland. So I am using it on Wayland

**Comment by letsfindaway** [comment]
Please switch to X11 and try it again. If you google for "wayland screenshot problem" you get a lot of entries. The underlying problem is, that Wayland restricts the access to screen content and does not allow to take screenshots from areas of the screen not generated by the current application.

What other options were not working on X11 with OpenBoard?

**Comment by omkardongre** [comment]
On X11 none of the option displayed on desktop is working. 
![Screenshot from 2022-10-03 16-35-06](https://user-images.githubusercontent.com/44136758/193563228-3eaa3a62-decf-475f-a9c9-f080335db34d.png)

**Comment by letsfindaway** [comment]
See "Known issues" for Linux in the [Release Notes](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.3):

> Linux
>
> - In Desktop Mode, Gnome Dock should be set to bottom position to workaround the issue with the Openboard left palette not beeing usable from above it (cf. https://bugreports.qt.io/browse/QTBUG-81341 for more details).

**Comment by idoric** [comment]
> The underlying problem is, that Wayland restricts the access to screen content 

It's true, and it's a good thing that an application can't monitor our screen without us knowing about it.

> and does not allow to take screenshots from areas of the screen not generated by the current application.

It's false. Under Wayland, GNOME's built-in screenshot system allows you to select an arbitrary area of the screen, you can use OBS (flatpaked or not) to stream your (wayland) desktop, with Kooha (flapaked) you can select a portion of the screen to record (at least as long as we don't want the sound), with Normcap (flatpaked) also you can select a region on the screen, etc.

The only condition is to use the ScreenCast portal (org.freedesktop.portal.ScreenCast), which means it should work inside and outside the Flatpak sandbox, in Wayland and X11, and on GNOME and KDE (and probably others). But there is a big difference with what was done before: the application asks for permission, which the user is free to accept or refuse.

**Comment by letsfindaway** [comment]
> > The underlying problem is, that Wayland restricts the access to screen content
> 
> It's true, and it's a good thing that an application can't monitor our screen without us knowing about it.
> 
> > and does not allow to take screenshots from areas of the screen not generated by the current application.
> 
> It's false. Under Wayland, GNOME's built-in screenshot system allows you to select an arbitrary area of the screen, you can use OBS (flatpaked or not) to stream your (wayland) desktop, with Kooha (flapaked) you can select a portion of the screen to record (at least as long as we don't want the sound), with Normcap (flatpaked) also you can select a region on the screen, etc.
> 
> The only condition is to use the ScreenCast portal (org.freedesktop.portal.ScreenCast), which means it should work inside and outside the Flatpak sandbox, in Wayland and X11, and on GNOME and KDE (and probably others). But there is a big difference with what was done before: the application asks for permission, which the user is free to accept or refuse.

Thanks for your explanation! Yes, you're right. Would you like to create a feature request for this? I could imagine that such a feature could be part of the upcoming 1.7 releases. It would be helpful if you could add some pointers and links on how to use the ScreenCast portal correctly.

If you have experiences in using this API: could you even provide a PR for this based on 1.7-dev? To give you a pointer: Grabbing is performed here in the `1.7-dev` branch:
https://github.com/OpenBoard-org/OpenBoard/blob/47a96e1d6bbdc0250977d22f1b79f11fcc1cbeee/src/core/UBDisplayManager.cpp#L416-L428.

**Comment by omkardongre** [comment]
As this is a known issue in latest release should I closed this ticket and expect this functionality to be resolved by next release?

**Comment by idoric** [comment]
I contacted someone likely to answer much better than me, but unfortunately I have no answer. It's been a long time since I've written c++, and even longer since I've tinkered with a few things using Qt, but I found these few links that might prove useful:

- https://flatpak.github.io/xdg-desktop-portal/ (see especially org.freedesktop.portal.ScreenCast and org.freedesktop.portal.Screenshot)
- https://doc.qt.io/qt-5/qtdbus-index.html
- https://github.com/flatpak/xdg-desktop-portal
- https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#For_developers (with the address of a matrix salon to ask for help)

I hope this can help.

**Comment by letsfindaway** [comment]
I have opened feature request #679, so you may close the issue here. @idoric Thanks for the pointers! I tried to add some example code, even if it is in other languages.
