### ISSUE TITLE
[Bug] Sometimes AnyEmbed does not work with certain iframes

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#691]
Hi,
I love using the AnyEmbed application to integrate online content in my class.
I spotted a bug though. Sometimes iframe works, sometimes it does not.

For example it works with iframes from Learning App (to test, try to integrate : <iframe src="https://learningapps.org/watch?app=26574594" style="border:0px;width:100%;height:500px" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"></iframe> )

And it does not work with DigiSlides (for exemple, try to integrate : <iframe src="https://ladigitale.dev/digislides/s/6351507e1b3de/" allowfullscreen frameborder="0" width="100%" height="500"></iframe> )

I tried to change arguments but no difference...

**Comment by letsfindaway** [comment]
This is most probably because of the outdated browser engine using `QWebKit` in OpenBoard 1.6.x. The upcoming version 1.7.0 will be based on `QWebEngine`. I tested both of your examples there and both are working.

If you embed a web page using features not available in the `QWebKit` engine, then they will not work. I assume you will have the same problems when you try the URL https://ladigitale.dev/digislides/s/6351507e1b3de/ with the built-in Web Browser of OpenBoard - and the URL will work well with OpenBoard 1.7.0.

So it is not the fault of AnyEmbed - it is the underlying browser engine.

**Comment by SeeDborg** [comment]
Good news, I look forward to see it work :)
