### ISSUE TITLE
Offer another distribution system for gnu/linux distros

### ISSUE THREAD

**Issue by haevalencia** [OpenBoard-org/OpenBoard#77]
Currently only offer a package *.deb to install on Debian systems or derivatives which makes it difficult to use in other distributions by non-experienced users. 
The ideal would be to offer repositories for different distros but it is hard work to maintain them, luckily there are currently "universal" options like Flatpak which would be a good idea.

**Comment by deisi** [comment]
I had the same Idea and started to look into it. I thought how hard can it be and started to see how far I get with building a flatpak package. However I hit a point where I don't get further. My current manifest can be found [here](https://pastebin.com/1r1JCfmp).

It compiles downloads the code, compiles the third party dependencies and starts to build OpenBoard. But sadly it fails because it calls the lsb_release script at some point, and this script is not availabe within the runtime I use. 

```
Info: creating stash file /home/malte/Software/OpenBoard.flatpak/.flatpak-builder/build/OpenBoard-6/.qmake.stash
sh: lsb_release: command not found
```

I tried to add it to the build env but I don't know how. So if somebody want to help on with this, it would be really nice.

**Comment by haevalencia** [comment]
@TingPing I have seen that you are willing to help with this topi in other issues, (only if you have time look here). Thank you.

**Comment by his10** [comment]
https://github.com/OpenBoard-org/OpenBoard/issues/58#issuecomment-446687339 - OpenBoard is now available as Flatpak.

**Comment by deisi** [comment]
I guess this can be closed now or?
