### ISSUE TITLE
Version 1.7 release date ?

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#793]
Everything is in the title :) 

Do you have an estimated release date for the upcoming version 1.7 ?

Regards.

**Comment by kaamui** [comment]
For now, OpenBoard 1.7.0 is supposed to be released near October, but a lot of unexpected issues are popping every day, making it hard to be confident about release dates 😄 

Mainly, I am struggling with macOS issues (videos crash with Qt 6.4, not with Qt 6.5, but impossible to sign the app with Qt 6.5 the same way it works with all the other Qt versions, no universal package with Qt 5.15 until Qt 5.15.10 => cool MacPorts provides Qt 5.15.10 binaries, oh wait you can't deploy a WebEngine-based app with binaries provided by MacPorts because they are not using rpath and macdeployqt fails without it, etc...). 

Yesterday I finally found out (with Qt's help) how to get rid of Qt 6.5 signing issues, so I want to say that now we can go further, but who knows ^^

Also yesterday, I discovered that every Google Maps application, no matter what version you have, or what OS, suddenly stopped working because we probably hit a certain "site traffic", so the API Key used in this app is somehow blocked until I go on the billing board of Google Maps and start paying. 

I'm also waiting for some translations in italian and german, but teachers in charge of it are also handling the start of the year (school year) so it takes time.

Note that I always release a new version in Github, before deploying it in our schools, or before updating the website.

**Comment by SeeDborg** [comment]
Thanks for the answer :)
Maybe you should think about releasing a beta version before ? So more people can test it for you (and more bugs will appear, good luck ^^).

(OK, I just saif that because how hard I try, I never succeed to compile 1.7...)

**Comment by kaamui** [comment]
> (OK, I just saif that because how hard I try, I never succeed to compile 1.7...)

Where do you struggle at ? What OS ? Did you see the wiki pages ?

**Comment by kortenkamp** [comment]
Let me know if I can help with the German translation.

**Comment by SeeDborg** [comment]
> > (OK, I just saif that because how hard I try, I never succeed to compile 1.7...)
> 
> Where do you struggle at ? What OS ? Did you see the wiki pages ?

Windows, I saw the Wiki, and there is always one software or another that causes issues on install or running :(
Anyway it would be much easier if you compiled a beta from times to times, isn't it a good idea ? I guess I'm not the only one that can't compile a version every week.

**Comment by kaamui** [comment]
> > > (OK, I just saif that because how hard I try, I never succeed to compile 1.7...)
> 
> Windows, I saw the Wiki, and there is always one software or another that causes issues on install or running :( Anyway it would be much easier if you compiled a beta from times to times, isn't it a good idea ? I guess I'm not the only one that can't compile a version every week.

I've a lot of things to handle, and releasing a new version implies writing the changelog, which is quite big for 1.7.0. I simply don't have the time for it. 

But I can help you step by step with compiling from source, and your feedback on it will help me improve the wiki page for Windows. Tell me explicetly what's happening and I'll try to help.

**Comment by protozyko** [comment]
> edit : @SeeDborg https://drive.google.com/file/d/1eI4pJjN6Rd35HHivWJZ7mTrQaFsWsi7t/view?usp=sharing

I have been using 1.7-a.230829 for some days now. I notice that the ability to paste directly from windows "snipping" tool is gone. This is a feature I use a lot. Sure you have this feature built into Openboard, but when using multiple screens windows snipping is much faster.
Also I notice some lag when saving documents, sometimes it crashes. Had to turn off autosave which helped on the crashing bit.

**Comment by SeeDborg** [comment]
Thanks for the upload, I did not notice it until now !
I'll try that :)
Is there a list of the new features that I can find somewhere ?

**Comment by letsfindaway** [comment]
> Also I notice some lag when saving documents, sometimes it crashes. Had to turn off autosave which helped on the crashing bit.

This might be worth a separate issue with as much information as possible. Are there any special circumstances when this happens? Anything in the log file?

> Is there a list of the new features that I can find somewhere ?

You can find my list of changes here: https://github.com/letsfindaway/OpenBoard/wiki/Changes-in-OpenBoard-1.7.0. This is not the official change log, but a condensed list of the IMHO most important changes,

**Comment by SeeDborg** [comment]
Thanks for the link :)

Could I ask for a compiled latest version please ?
I'm using the old one for a while now and I spotted some bugs, I'd like to see if they are fixed before I spam the issues here ^^

While we're at it, is the latest version releasing soon in "official" release ?

**Comment by michelwend** [comment]
Hello,
Let me ask you if the new version 1.7 for windows will be available again this year. It’s just to know if I’m waiting a little bit to update my image. I am well aware that it is volunteer work and that you will release this version only when it is functional. Thanks again for this great software.
