### ISSUE TITLE
Context menus on wrong monitor

### ISSUE THREAD

**Issue by optikkore** [OpenBoard-org/OpenBoard#812]
Windows 1.6.4, when using two displays in extended mode, we can swap the control and display screen within the options. But when clicking the openboard main menu or export or anything that would pop up a context menu it still displays on the primary monitor. Is it a setting in the config or something i can fix easily?

**Comment by letsfindaway** [comment]
This is a known problem caused by a bug in Qt. See  the [Release notes](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.4) and #536.

I currently don't have an overview of the status of this bug. But I just tested with the upcoming 1.7.0 release and Qt 5.15.8 on openSUSE Linux and the problem does not occur to me.

**Comment by optikkore** [comment]
@letsfindaway Thank you, yes I compiled 1.7.0 with QT 5.15.2 for windows and it also worked, sorry about that.

**Comment by kaamui** [comment]
Please be aware that we don't compile with Qt 5.15.2 because of another issue where right-clicking on a `QGraphicsItem` (or maybe it's only for `QGraphicsTextItem` I don't remember) would make the app crash.

**Comment by optikkore** [comment]
@kaamui sorry for coming back to this, is qt 6.6.0 okay?

**Comment by kaamui** [comment]
> @kaamui sorry for coming back to this, is qt 6.6.0 okay?

Next Windows should be working with Qt 6.7. This issue should then no longer appear

**Comment by zikkuratti** [comment]
![изображение](https://github.com/user-attachments/assets/cbd7b793-2b2f-4bad-93c3-45452e45d6a9)
