### ISSUE TITLE
standard zoom cannot be set

### ISSUE THREAD

**Issue by slmnzk** [OpenBoard-org/OpenBoard#833]
When you edit the ZoomBase setting in the config, it automatically resets to 1.0005 if it goes beyond 1.0 - 1.01.

is there any need for this? is there any other way to change it? when you open pdf files with a large number of pages, it is quite tedious to zoom in on each page.

**Comment by letsfindaway** [comment]
Currently there is no setting for a standard zoom factor.

`ZoomBase` is something different: it is used when zooming with the mouse wheel to calculate a zoom factor as `pow(zoomBase, wheelAngle)`, so it is the base of an exponential function - that's why it is called `ZoomBase`. And that's also the reason for the limitation. With larger values the exponential function would explode to very high zoom factors.

**Comment by slmnzk** [comment]
that makes sense now, thank you.
