### ISSUE TITLE
[Wiki suggestion] Folder for custom widgets

### ISSUE THREAD

**Issue by letsfindaway** [OpenBoard-org/OpenBoard#866]
The wiki page https://github.com/OpenBoard-org/OpenBoard/wiki/Creating-Web-Widgets suggests installing custom widgets by copying them to the program installation folder. I would instead suggest to copy them to the `interactive content` folder in the user's home directory just where `OpenBoardUser.config` is located for several reasons:

- IMHO a user should not modify the content of a program installation folder at all.
- When updating OpenBoard, any modifications in this folder are lost. If the widget is instead installed in the user's home directory, the custom widgets are preserved.
- It does not require `root` or administrator privileges.
- On Linux, the folder location is the same, no matter whether the official package is installed, some package from a distribution or a Flatpak package.

See https://github.com/letsfindaway/OpenBoard/wiki/Custom-widgets#custom-widget-installation for the folder locations I would suggest. Of course you should verify the locations given for Windows and MacOS, but is the same as you mentioned on https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration.

**Comment by kaamui** [comment]
I would prefer to find a way to add you to the members of the official repo. You're daily helping the project for years now and it's the natural continuation of such commitment. I sent you an invitation, and will try to find the correct set of permissions so you can do these kind of contributions without asking my permission.

I'll of course ask you to limit yourself to editing the community-driven parts of the wikis, and to continue to go trough the pull request process for your commits. 

Tell me if that's OK for you. 

Concerning the `interactive content` suggestion, I hesitated but the wiki tends to invite web devs to quickly go into the project to dev their web widgets, I wanted it to remain "not technical". I'll add more detail on the way to submit it via a pull request, to mention the cloning of the repository.

I also chose to present it that way because I'm not a fan of the "Web" folder created to put al the user-created content, I like the idea that web devs see their contribution directly side-by-side with the official widgets. 

I'll mention it though, for non `root/admin` users

**Comment by letsfindaway** [comment]
> I would prefer to find a way to add you to the members of the official repo. You're daily helping the project for years now and it's the natural continuation of such commitment. I sent you an invitation, and will try to find the correct set of permissions so you can do these kind of contributions without asking my permission.

Thanks! I accepted the invitation.
 
> I'll of course ask you to limit yourself to editing the community-driven parts of the wikis, and to continue to go trough the pull request process for your commits.
> 
> Tell me if that's OK for you.

This is OK! 

> 
> Concerning the `interactive content` suggestion, I hesitated but the wiki aims to invite web devs to quickly go into the project to dev their web widgets, I wanted it to remain "not technical". I'll add more detail on the way to submit it via a pull request, to mention the cloning of the repository.
> 
> I also chose to present it that way because I'm not a fan of the "Web" folder created to put al the user-created content, I like the idea that web devs see their contribution directly side-by-side with the official widgets. I also don't like the space between interactive and content 😄
> 
> I'll mention it though, for non `root/admin` users
> 
> edit : I forgot that the `Web` folder was not mandatory. I'll edit the page to invite users to do it the right way. thanks for the heads up

Yes, any widget put directly to the interactive content will show up at top level of applications.
