### ISSUE TITLE
[Bug] Crash when importing image

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#879]
Everytime I use the fonctionnalité "add an image" in the documents section, the program is crashing...

**Comment by letsfindaway** [comment]
Can reproduce. Some more information:

One way to reproduce the bug is as follows: go to Documents mode, select Add, and then Add Images. After selecting an image, a new page is added. When you then double-click on the thumbnail of the newly added page with the image, OpenBoard crashes.

Here a traceback at the point of failure:
![grafik](https://github.com/OpenBoard-org/OpenBoard/assets/35591413/aa109224-5ef8-401f-b8d7-a2b6b8f0c7e7)

In `UBBoardThumbnailsView::ensureVisibleThumbnail` the member variable `mThumbnails` does not contain thumbnails for the added pages. Therefore an index-out-of-bounds error occurs.

**Comment by letsfindaway** [comment]
This problem is already fixed with commit 49ac85cfcb4f3f81110ea3ce7aa55c0380799e4e
