### ISSUE TITLE
Setting: Specify Document Directory

### ISSUE THREAD

**Issue by melLML** [OpenBoard-org/OpenBoard#88]
I would like to have a document directory setting, so I could specify, where the OpenBoard documents are saved, but leaving the location for all other files untouched.

**Comment by freeheel3r** [comment]
Hi,
This is currently not possible, unfortunately. The document folder is always a sub-folder of the user folder (e.g ~/.local/share/OpenBoard/**document/**, see [here](https://github.com/OpenBoard-org/OpenBoard/wiki/Settings#appdatadirectory)). There is no setting to specify the document folder directly.

However, you can create a symbolic link (shortcut) in its place to point somewhere else, if you'd like. So you could store your documents wherever is most convenient for you, and place a shortcut to your folder in OpenBoard's user folder. As long as you name it "document", it should work.

I'll label this as a feature request all the same, perhaps someone will want to implement this setting.

**Comment by stavpup** [comment]
On windows, documents are stored in AppData\Local\OpenBoard\document
Pictures are stored in Pictures\OpenBoard etc

**Comment by fabian-bouche-liferay** [comment]
The user document directory is defined here and is indeed a /document subdirectory of the user data directory:

https://github.com/OpenBoard-org/OpenBoard/blob/1665e2e570e5e76c75d9e8a4b7e9a3f0c5071736/src/core/UBSettings.cpp#L1065

If it is ok for you to move the whole user data directory somewhere else, this is actually possible because:

https://github.com/OpenBoard-org/OpenBoard/blob/1665e2e570e5e76c75d9e8a4b7e9a3f0c5071736/src/core/UBSettings.cpp#L954

And you can change the location of that data directory with the `App/DataDirectory` setting:
https://github.com/OpenBoard-org/OpenBoard/blob/1665e2e570e5e76c75d9e8a4b7e9a3f0c5071736/src/core/UBSettings.cpp#L161

I've added the following setting in the ./etc/OpenBoard.config:

```
[App]
DataDirectory=C:/temp/openboard
```

And the documents are now stored under the C:\temp\openboard location.
