### ISSUE TITLE
[Bug] QwebEngine issues with Qt 5, not with Qt 6.

### ISSUE THREAD

**Issue by sebojolais** [OpenBoard-org/OpenBoard#898]
### Describe the bug
It seems that some websites are rendered with some issues.
For example, this website is a useful timer : https://achampollion.forge.aeif.fr/tuxtimer/
It is displayed as expect in:
- `Chromium 121.0.6167.184`
- `OpenBoard 1.7.1` compiled with Qt 6.4.0

But the circle arc is not shown with `OpenBoard 1.7.0`, official release compiled with `Qt 5.15.6`
For more details, this SVG part of the html page is not shown:
```
    <svg id="horloge" viewBox="0 0 100 100">
        <path id="myCircle" fill="#0000ff" d="M 60.395584540887974 1.0926199633097227 A 50 50 0 0 0 50 0 L 50 50 Z"></path>
    </svg>

```

### To Reproduce
- Open a web browser
- Go to this url: https://achampollion.forge.aeif.fr/tuxtimer/
- Click on ‘+’ button
- You will see a blue circle arc
- Open OpenBoard 1.7.0
- Go to Web mode
- Open the same url: https://achampollion.forge.aeif.fr/tuxtimer/
- You will never see the blue circle arc

It seems that `QwebEngine` of `Qt 5` works bader than `Qt 6`.
Any idea on this issue is welcome.
Is there a workaround for this issue?

### Context
  - reproducibility : `systematic`
  - OpenBoard version :
      - bug happens with : `1.7.0`
      - bug doesn't happen with : `1.7.1-rc.240202` `dev branch` and `Qt 6.4.0`
  - OS : 
      - bug happens with : `Linux`
      - didn't check : `Windows` `macOS` 
  - Installation source : `OpenBoard download page`
  
### Additional context
- OS(es) detailed version (for the ones you reproduced the bug on) : 
    - Linux : `Description:    KDE neon 5.27`
- number and resolution of monitors : `1`

**Comment by letsfindaway** [comment]
This is fact a problem understanding the CSS of the linked web page. Using the web inspector I found:

![grafik](https://github.com/OpenBoard-org/OpenBoard/assets/35591413/4e81959b-786c-46b0-af61-6c73fa1cee0c)

The yellow exclamation mark says "Invalid property value". If I use a number for `scaleX`, i.e. `-1` in this case, then it works. Other browsers and also Qt 6 seems however to understand the percentage value. I think percentage values are allowed in this case by most browsers, but are not accepted by the version of `QWebEngine` bundled with Qt 5.15. See https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale which explicitly allows a percentage value. However https://drafts.csswg.org/css-transforms/#funcdef-transform-scale, which is linked by the Mozilla web page and should be the authoritative source, only allows a number for scale, while it allows percentage for translate. 

So it seems that most web browsers allow more than required by the W3C specification. Older versions of `QWebEngine` however have been more strict.

You can now argue whether it is a problem with the web site or with the browser engine.

This problem might also affect other web sites using CSS transform with percentage values. OpenBoard cannot do anything about it, but at least we now have an explanation.

**Comment by letsfindaway** [comment]
Do you have contact to the author of this nice timer application? I have seen on https://forge.aeif.fr/achampollion that he updated the app just a few hours ago, so he could probably also change the `-100%` to `-1`, so that it conforms to the W3C specification ans also works with the web engine of Qt 5.

Unrelated to that, I have seen that he also created some other widgets as OpenBoard Apps and I would like to remind him to assign **unique** ids to his widgets in the `config.xml`. The same applies to most of the widgets listed here: https://forge.aeif.fr/svallet/openboard-applications.

I cannot open an issue there as registration requires an e-mail address from an educational instance.

**Comment by letsfindaway** [comment]
One example is https://forge.aeif.fr/svallet/openboard-applications/-/blob/main/compte_est_bon.wgt/config.xml?ref_type=heads, where the id is `http://uniboard.mnemis.com/widgets/notes`. This is the id of the built-in Notes widget of OpenBoard.  Another is https://forge.aeif.fr/svallet/openboard-applications/-/blob/main/nombre_en_lettres.wgt/config.xml?ref_type=heads with a very unspecific id of `www.mathix.org`, which is also used in https://forge.aeif.fr/svallet/openboard-applications/-/blob/main/puzzle-zukei.wgt/config.xml?ref_type=heads.

Some ids are unique in your context, but not generally like "Fraction".

Not in your list, but the ids in https://forge.aeif.fr/achampollion/syllabux, https://forge.aeif.fr/achampollion/seyes and https://forge.aeif.fr/achampollion/tuxtimer all use `http://openboard.org/widgets/myfirstwidget` as id. 

What I would generally like for the id is

- That it is **created by the author or maintainer** of the widget, so that it is the same no matter where somebody downloads the widget.
- That it is **globally unique**. There are several techniques to achieve this. The existing widgets use a URI for this (see https://en.wikipedia.org/wiki/Uniform_Resource_Identifier). This is something that looks like a URL in many cases, but does not necessarily point to an existing web page. The host part should contain a domain which the author controls. This makes it globally unique and allows me to manage the names. For example when I would create a widget, I would assign an id like `http://letsfindaway.de/openboard/widgets/myAwesomeWidget` to it. because I own `letsfindaway.de` I'm sure it cannot overlap with any other id. The structure behind the domain is just for my own purposes.

**Comment by sebojolais** [comment]
Ok, I fixed it in my side and I keep it in mind. 
I close the issue.
Many thanks,
