### ISSUE TITLE
OpenBoard not exporting file to pdf (only exporting the empty file or overlay only)

### ISSUE THREAD

**Issue by mihamc** [OpenBoard-org/OpenBoard#944]
### Describe the bug
I try to export a file on which I wrote and OpenBoard keeps spinning until I force quit. At first few trials the file exported was empty, but lately it exports the overlay (my writing on it) but not the original file. This file has only 17 pages... I tried to cut it to half and that doesn't work either. However, I am able to export other files.

I tutor students in math and I need to be able to export files after the sessions. I am at a standstill and don't know what to do - anything you can think that I should try?

If I re-install OpenBoard will I lose all my folders? I might do this after the school year is done, but can't do it now.

I use OpenBoard on a Mac, MacOS Sonoma 14.4.1.

Thank you!

**Comment by letsfindaway** [comment]
Please provide more information.

- What version of OpenBoard are you using?
- You say you can export other files - so what is special about the one failing?
- Can you provide a failing document as UBZ file so that others can eventually reproduce the problem?

**Comment by mihamc** [comment]
Thank you, I went around this. Seems the original file was corrupted. After printing it, taking the piece of the pdf that i need it and scanning it back I could use openboard successfully to write on it and export it.
We can close this issue.

**Comment by stlinuxgit** [comment]
I meet this issue.  openboard version is 1.7.1 under win10.

**Comment by letsfindaway** [comment]
Did you see the [last comment](https://github.com/OpenBoard-org/OpenBoard/issues/944#issuecomment-2083806678) of the original poster? Here the problem was the original PDF file, which probably contained some specific things which could not be handled by OpenBoard's built-in PDF mixer. To track that further my questions are the same (except the version, which you already provided):

> Please provide more information.
> 
> * You say you can export other files - so what is special about the one failing?
> * Can you provide a failing document as UBZ file so that others can eventually reproduce the problem?
> * While OpenBoard is spinning, can you check whether there is high CPU usage or high memory consumption?

I hope you can imagine: without being able to reproduce your problem we cannot do anything about it. So we need a scenario where we can also reproduce it on our side.
