### ISSUE TITLE
Desktop mode mask darken screenshots on linux

### ISSUE THREAD

**Issue by lucientisserand** [OpenBoard-org/OpenBoard#99]
Hi there,
I have an issue.
WM : openbox
Distro : Debian Stretch 9.1

In desktop mode the screen is darkened which seems to be an intended feature for the purpose of accounting for the focus still on openboard, right ?
The problem is that the screenshot feature in desktop mode keeps the dark mask while proceeding (see pics for comparison of openboard screenshot with regular scrot).
Thus it remains unusable.
Is it specific to linux and/or openbox ? Don't know about other DE.
![image capturee-15-09-2017 15-05-15](https://user-images.githubusercontent.com/31990407/30483827-a1144bb2-9a28-11e7-8670-4bbe64b7dcfe.png)
![zone1505480749_431x256_scrot](https://user-images.githubusercontent.com/31990407/30483826-a114049a-9a28-11e7-9170-4a6c45369d2b.png)

Regards

**Comment by freeheel3r** [comment]
Hi,

This doesn't sound normal, the desktop mode shouldn't darken the screen. There is technically a window overlaid on the desktop but it should be completely transparent -- at least on other window managers.

There have been issues reported with desktop mode on some environments (see issue #66 for example); there are a lot of inconsistencies between different window managers, even getting everything to work the same way on KDE, Gnome, Cinnamon and Unity was quite a headache. Fixing a problem on one environment tends to make it appear on another...

Unfortunately I am not familiar at all with openbox and don't have a machine I can install it on in the immediate future. If someone wants to look into this issue I'll happily provide assistance however.

In the meantime I can only recommend checking if the problem comes from some openbox setting (maybe it always darkens the background when an application is full-screened?)

**Comment by lucientisserand** [comment]
Hi, thank you for your response.
Now that I know that it is not intended, and when you talked about the overlaid window, I just realized that **it was just the compositor drawing the shadow of that overlaid window.**
In my case, Compton is the compositor. I disabled the shadow for the window class "openboard" in ~/.config/compton.conf with that line :
`shadow-exclude = [ "i:e:openboard" ];`

Users experiencing this issue should have a look at their DE compositing preferences.
There may be preferences for disabling shadow for full-screen windows as default for users who do not encounter this issue.

I am not myself a dev, but maybe it is possible for openboard to block shadow from compositor or ask the WM for not being shadow-composited ?

An other way of fixing this issue for the user is disabling the compositor, but transparencies are thus not rendered.

1st Screenshot : Compositing fully enabled (source of issue)
![compositor enabled](https://user-images.githubusercontent.com/31990407/30523354-3a36915c-9be0-11e7-9e69-b727efda11ce.png)

2nd screenshot : Compositing completely disabled (thus no transparencies)
![compositor completely disabled](https://user-images.githubusercontent.com/31990407/30523362-640974ae-9be0-11e7-8760-2e208b93ad74.png)

3rd screenshot : Shadow excluded in compton.conf (everything is ok, although workaround differs between DEs)
![shadow only disabled](https://user-images.githubusercontent.com/31990407/30523379-afa00b80-9be0-11e7-8770-1868591daedf.png)

Solved for me, thanks for the cues.
